<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'etsy_config_account_title'} = 'Zugangsdaten';
MLI18n::gi()->{'etsy_config_account_prepare'} = 'Artikelvorbereitung';
MLI18n::gi()->{'etsy_config_account_price'} = 'Preisberechnung';
MLI18n::gi()->{'etsy_config_account_sync'} = 'Synchronisation';
MLI18n::gi()->{'etsy_config_account_orderimport'} = 'Bestellimport';

MLI18n::gi()->{'etsy_configform_sync_values'} = array(
    'no' => '{#i18n:configform_sync_value_no#}',
    'auto_zero_stock' => 'Automatische Synchronisierung mit Null-Bestand (empfohlen)',
    'auto' => 'Automatische Synchronisierung ohne Null-Bestand',
);

MLI18n::gi()->{'etsy_configform_sync_nozerostock_popup_label'} = 'Automatische Synchronisierung ohne Null-Bestand';
MLI18n::gi()->{'etsy_configform_sync_nozerostock_popup_text'} = 'Produkte, deren Lagerbestand unter 1 fällt, werden auf “inaktiv” gesetzt und bei einer Lagerbestandsänderung nicht automatisch reaktiviert. Dadurch werden intransparente Gebühren verhindert.';
MLI18n::gi()->{'etsy_configform_sync_zerostock_popup_label'} = 'Automatische Synchronisierung mit Null-Bestand (empfohlen)';
MLI18n::gi()->{'etsy_configform_sync_zerostock_popup_text'} = 'Die Option bewirkt, dass Ihre Angebote reaktiviert werden, wenn der Lagerbestand im Webshop > 0 ist. Bei einer Lagerbestandsänderung auf < 1 werden Ihre Angebote deaktiviert. Für die Reaktivierung von Angeboten wird Ihnen seitens Etsy Gebühren berechnet.';

MLI18n::gi()->{'etsy_config_carrier_option_group_additional_option'} = 'Zusätzliche Option:';
MLI18n::gi()->{'etsy_config_carrier_option_group_marketplace_carrier'} = 'Vom Marktplatz unterstützte Versanddienstleister:';
MLI18n::gi()->{'etsy_config_free_text_attributes_opt_group'} = 'Zusatzfelder';
MLI18n::gi()->{'etsy_config_free_text_attributes_opt_group_value'} = 'Ordnen Sie es dem Freitextfeld in einer bestimmten Reihenfolge zu';
MLI18n::gi()->{'etsy_config_carrier_option_matching_option'} = 'Matchen der vom Marktplatz unterstützten Versanddienstleister mit den im Shop-System definierten Versanddienstleister';
MLI18n::gi()->{'etsy_config_carrier_matching_title_marketplace_carrier'} = 'Vom Marketplace unterstützte Versanddienstleister';
MLI18n::gi()->{'etsy_config_carrier_matching_title_shop_carrier'} = 'Im Shop-System definierte Versanddienstleister (Versandoptionen)';
MLI18n::gi()->{'etsy_config_item_preparation_readiness_state_ready_to_ship'} = 'Versandfertig';
MLI18n::gi()->{'etsy_config_item_preparation_readiness_state_made_to_order'} = 'Auf Bestellung gefertigt';

