<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Amazon_CheckinForm__Price'} = 'Price';
MLI18n::gi()->{'Amazon_CheckinForm__Amount'} = 'Quantity';
MLI18n::gi()->{'Amazon_CheckinForm__ShippingTime'} = 'Handling time (in days)';
MLI18n::gi()->{'Amazon_CheckinForm__ShopPrice'} = 'Shop';
MLI18n::gi()->{'Amazon_CheckinForm__SuggestedPrice'} = 'Calculated (acc. to Configuration)';
MLI18n::gi()->{'Amazon_CheckinForm__HitPrice'} = 'Price Hit';
MLI18n::gi()->{'Amazon_CheckinForm__AvailibleAmount'} = 'Available';
MLI18n::gi()->{'Amazon_CheckinForm__SuggestedAmount'} = 'Calculated (acc. to Configuration)';
