<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'configform_quantity_values__stock__title'} = 'Utilizar estoque da loja';
MLI18n::gi()->{'configform_quantity_values__stock__textoption'} = '';
MLI18n::gi()->{'configform_quantity_values__stocksub__title'} = 'Utilizar estoque da loja menos valor do campo à direita';
MLI18n::gi()->{'configform_quantity_values__stocksub__textoption'} = '1';
MLI18n::gi()->{'configform_quantity_values__lump__title'} = 'Taxa fixa (da cAmpo à direita)';
MLI18n::gi()->{'configform_quantity_values__lump__textoption'} = '1';
MLI18n::gi()->{'configform_price_addkind_values__percent'} = 'x% de acréscimo / desconto no preço da loja';
MLI18n::gi()->{'configform_price_addkind_values__addition'} = 'x de acréscimo / desconto no preço da loja';
MLI18n::gi()->{'configform_sync_value_auto'} = 'Sincronização automática através de CronJob (recomendado)';
MLI18n::gi()->{'configform_sync_value_no'} = 'Sem sincronização';
MLI18n::gi()->{'configform_sync_values__auto'} = '{#i18n:configform_sync_value_auto#}';
MLI18n::gi()->{'configform_sync_values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'configform_stocksync_values__rel'} = 'Pedido reduz estoque na loja (recomendado)';
MLI18n::gi()->{'configform_stocksync_values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'marketplace_configuration_orderimport_payment_method_from_marketplace'} = 'Apply the payment method submitted by the marketplace';
