<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'configform_check_entries_error'} = 'configform_check_entries_error';
MLI18n::gi()->{'configform_quantity_value_error'} = 'O campo Quantidade deve ser um número decimal.';
MLI18n::gi()->{'configform_price_factor_error'} = 'O campo Acréscimo / Desconto deve ser numérico.';
MLI18n::gi()->{'configform_price_signal_error'} = 'O campo Decimais deve ser um número decimal.';
MLI18n::gi()->{'configform_ust_error'} = 'O Imposto deve ser numérico.';
