<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sInventorySyncByService'} = 'Preços e estoques foram sincronizados com sucesso nos seguintes Marketplaces:';
MLI18n::gi()->{'sOrderStatusSyncByService'} = 'Situação dos pedidos foram sincronizados com os seguintes Marketplaces:';
MLI18n::gi()->{'sAddItemProductWithZeroQuantity'} = 'Artigos com estoque 0 (zero) foram desconsiderados.';
