<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameCdiscount'} = 'Cdiscount';
MLI18n::gi()->{'cdiscount_label_title'} = 'Titre Cdiscount';
MLI18n::gi()->{'cdiscount_category'} = 'Catégorie Cdiscount';
MLI18n::gi()->{'cdiscount_label_item_id'} = 'Identifiant d\'article';
MLI18n::gi()->{'cdiscount_search_by_title'} = 'Rechercher par titre';
MLI18n::gi()->{'cdiscount_search_by_ean'} = 'Rechercher par code EAN';
MLI18n::gi()->{'cdiscount_label_not_matched'} = 'ne pas classer';
MLI18n::gi()->{'cdiscount_upload_explanation'} = 'En règle générale, les produits téléchargés sont placés sur Cdiscount en quelques heures.
Si le produit n\'est pas déjà disponible sur Cdiscount, cela peut prendre jusqu\'à 24 heures.
Vous trouverez ensuite les articles sur votre compte revendeur Cdiscount.';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_marketplace_carrier'} = 'Porteurs suggérés par CDiscount';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_carrier'} = "Sélectionner l'entreprise de transport dans une boutique en ligne Champ de texte libre (commandes)";
MLI18n::gi()->{'cdiscount_config_carrier_option_matching_option_carrier'} = "Faire correspondre les entreprises de transport suggérées par CDiscount avec les prestataires de services d'expédition du module d'expédition de la boutique en ligne.";
MLI18n::gi()->{'cdiscount_config_carrier_option_freetext_option_carrier'} = 'Transférer la société de transport sous forme de somme forfaitaire à partir du champ de texte';
MLI18n::gi()->{'cdiscount_config_carrier_matching_title_shop_carrier'} = "Fournisseur de services d'expédition à partir du module Webshop Shipping";
MLI18n::gi()->{'cdiscount_config_carrier_matching_title_marketplace_carrier'} = 'Porteurs suggérés par CDiscount';
MLI18n::gi()->{'cdiscount_config_carrier_option_orderfreetextfield_option'} = 'magnalister ajoute un champ de texte libre dans les détails de la commande';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_additional_option'} = 'Options supplémentaires';
MLI18n::gi()->{'cdiscount_config_carrier_matching_title_marketplace_shipmethod'} = "Saisie manuelle d'un service de livraison";
MLI18n::gi()->{'cdiscount_config_carrier_option_freetext_option_shipmethod'} = 'Reprendre le montant forfaitaire du service de livraison à partir du champ de texte';
MLI18n::gi()->{'cdiscount_config_carrier_option_matching_option_shipmethod'} = "Faire correspondre le service de livraison avec les entrées du module d'expédition de Webshop";
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_shipmethod'} = "Sélectionner le service de livraison à partir d'une boutique en ligne Champ de texte libre (commandes)";
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_carrier'} = "Sélectionner l'entreprise de transport dans une boutique en ligne Champ de texte libre (commandes)";
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_shipmethod'} = "Sélectionner le service de livraison à partir d'une boutique en ligne Champ de texte libre (commandes)";
MLI18n::gi()->{'cdiscount_config_carrier_option_group_marketplace_carrier'} = 'Porteurs suggérés par CDiscount';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_carrier'} = "Sélectionner l'entreprise de transport dans une boutique en ligne Champ de texte libre (commandes)";
MLI18n::gi()->{'cdiscount_config_carrier_option_matching_option_carrier'} = "Faire correspondre les entreprises de transport suggérées par CDiscount avec les prestataires de services d'expédition du module d'expédition de la boutique en ligne.";
MLI18n::gi()->{'cdiscount_config_carrier_option_freetext_option_carrier'} = 'Transférer la société de transport sous forme de somme forfaitaire à partir du champ de texte';
MLI18n::gi()->{'cdiscount_config_carrier_matching_title_shop_carrier'} = "Fournisseur de services d'expédition à partir du module Webshop Shipping";
MLI18n::gi()->{'cdiscount_config_carrier_matching_title_marketplace_carrier'} = 'Porteurs suggérés par CDiscount';
MLI18n::gi()->{'cdiscount_config_carrier_option_orderfreetextfield_option'} = 'magnalister ajoute un champ de texte libre dans les détails de la commande';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_additional_option'} = 'Options supplémentaires';
MLI18n::gi()->{'cdiscount_config_carrier_matching_title_marketplace_shipmethod'} = "Saisie manuelle d'un service de livraison";
MLI18n::gi()->{'cdiscount_config_carrier_option_freetext_option_shipmethod'} = 'Reprendre le montant forfaitaire du service de livraison à partir du champ de texte';
MLI18n::gi()->{'cdiscount_config_carrier_option_matching_option_shipmethod'} = "Faire correspondre le service de livraison avec les entrées du module d'expédition de Webshop";
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_shipmethod'} = "Sélectionner le service de livraison à partir d'une boutique en ligne Champ de texte libre (commandes)";
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_carrier'} = "Sélectionner l'entreprise de transport dans une boutique en ligne Champ de texte libre (commandes)";
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_shipmethod'} = "Sélectionner le service de livraison à partir d'une boutique en ligne Champ de texte libre (commandes)";
