<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Cdiscount_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'Cdiscount_CheckinForm__Amount'} = 'Quantité';
MLI18n::gi()->{'Cdiscount_CheckinForm__ShippingTime'} = 'Livraison (en jours)';
MLI18n::gi()->{'Cdiscount_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'Cdiscount_CheckinForm__SuggestedPrice'} = 'Calculé (d\'après la configuration)';
MLI18n::gi()->{'Cdiscount_CheckinForm__HitPrice'} = 'Prix favori';
MLI18n::gi()->{'Cdiscount_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'Cdiscount_CheckinForm__SuggestedAmount'} = 'Montant calculé d\'après la configuration';
MLI18n::gi()->{'Cdiscount_CheckinForm__Condition'} = 'État de l\'article';
MLI18n::gi()->{'Cdiscount_CheckinForm__ListingType'} = 'Type de listing';
MLI18n::gi()->{'Cdiscount_CheckinForm__Conditions__new'} = 'Neuf';
MLI18n::gi()->{'Cdiscount_CheckinForm__Conditions__not_specified'} = 'Pas précisé';
MLI18n::gi()->{'Cdiscount_CheckinForm__Conditions__used'} = 'D\'occasion ';
MLI18n::gi()->{'Cdiscount_CheckinForm__BuyingMode'} = 'Mode d\'achat';
MLI18n::gi()->{'Cdiscount_CheckinForm__BuyingModes__buy_it_now'} = 'Offre directe ';
MLI18n::gi()->{'Cdiscount_CheckinForm__BuyingModes__auction'} = 'Vente aux enchères';
MLI18n::gi()->{'Cdiscount_CheckinForm__BuyingModes__classified'} = 'Classé';
MLI18n::gi()->{'Cdiscount_CheckinForm__ShippingMode'} = 'Mode de livraison';
MLI18n::gi()->{'Cdiscount_CheckinForm__ShippingModes__custom'} = 'Sur mesure';
MLI18n::gi()->{'Cdiscount_CheckinForm__ShippingModes__not_specified'} = 'Pas spécifié';
