<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'cdiscount_inventory_listing_quantity'} = 'Stock <br /> boutique / Cdiscount';
MLI18n::gi()->{'cdiscount_inventory_listing_price'} = 'Prix Cdiscount';
MLI18n::gi()->{'cdiscount_inventory_listing_status'} = 'Statut';
MLI18n::gi()->{'cdiscount_inventory_listing_status_new'} = 'Nouveau';
MLI18n::gi()->{'cdiscount_inventory_listing_status_update'} = 'Cdiscount actualise les produits';
MLI18n::gi()->{'cdiscount_inventory_listing_status_waiting'} = 'Submission des données à Cdiscount en cours';
MLI18n::gi()->{'cdiscount_inventory_listing_status_waiting_update'} = 'Cdiscount traite vos données ';
MLI18n::gi()->{'cdiscount_inventory_listing_status_active'} = 'Actif';
