<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Cdiscount_Label_sAutoMatchSuccess'} = 'Les articles avec les numéros EAN sont préparés.';
MLI18n::gi()->{'CDISCOUNT_BUTTON_LABEL_DELETE_COMPLETE_LOG'} = 'Effacer tous les rapports d\'erreur';
MLI18n::gi()->{'cdiscount_prepare_apply'} = 'Créer des nouveaux articles';
