<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparés avec succès';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparés';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Articles préparés non vérifiés';
MLI18n::gi()->{'Cdiscount_Productlist_Label_Price'} = 'Prix Cdiscount';
MLI18n::gi()->{'Cdiscount_Productlist_Filter_aPreparedStatus__OK'} = 'Préparés avec succès';
MLI18n::gi()->{'Cdiscount_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparés';
MLI18n::gi()->{'Cdiscount_Productlist_Filter_aPreparedStatus__OPEN'} = 'Articles préparés non vérifiés';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedType__Chinese'} = 'Vente aux enchères';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Prix fixe';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Prix fixe (boutique Cdiscount)';
MLI18n::gi()->{'Cdiscount_Productlist_Header_sPreparedType'} = 'Format d\'enchère';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Manual_Title_Single'} = 'Appariement individuel';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Manual_Title_Multi'} = 'Appariement multiple';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Auto_Title'} = 'Appariement automatique';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Auto_Summary'} = '%d des articles ont été appariés (matching) avec succès. <br/><br/>
	%d des articles n\'ont pas été appariés (matching) avec succès.<br/>
	Entre eux %d ont générés plusieurs résultats.
';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Manual_Desc'} = 'Vos articles vont être appariés (matched) avec les articles présents sur Cdiscount (comparaison des codes EAN et des titres).<br/><br/>
	Un rapport détaillé des résultats vous est ensuite délivré : échec ou succès et liste des produits similaires en cas de succès. Vous pouvez alors sélectionner lequel de ces produits est similaire ou assimilable au votre et apparier les dit produits (match).<br/><br/>
	La préparation est très précise et demande beaucoup de temps pour être effectuée. ';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Auto_Desc'} = 'Les articles, que vous avez sélectionnés, vont être préparés en arrière plan: Leurs numéros EAN pré-enregistrés seront automatiquement appariés (matching) avec les numéros EAN des articles correspondants sur Cdisount.<br/ ><br/ > Il est donc primordial de mettre à jour régulièrement les numéros EAN de chaque produit.';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Auto_Confirm'} = 'L\'appariement (matching) automatique se fait uniquement par la comparaison des codes EAN. Dans ce cas, il est alors possible que votre produit soit apparié avec un produit dont la description et des photos sont de moins bonnes qualités que les vôtres. Cela aura pour inconvénient de provoquer de mauvais résultats de présentation. L\'appariement automatique peut se révéler moins efficace qu\'un appariement manuel.<br/ ><br/ > RedGecko décline alors toutes responsabilités en cas d\'inexactitude de l\'article proposé.';
