<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_ERROR_GLOBAL'} = 'An error occured.
Please try again later. If the error does not disappear within the next few hours,
please contact us: https://www.magnalister.com/en/contact-us/ .';
