<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_TEXT_UPDATE_SUCCESS'} = 'The update was successfully completed. A list of important changes can be found at <a href="{#url#}" title="Change-Log">Change-Log</a>.';
MLI18n::gi()->{'ML_TEXT_INSTALL_SUCCESS'} = 'magnalister was successfully installed.';
MLI18n::gi()->{'sModal_updatePlugin_title'} = 'Updating magnalister plugin';
MLI18n::gi()->{'sModal_updatePlugin_content_init'} = 'Getting data from the magnalister server.';
MLI18n::gi()->{'sModal_updatePlugin_content_calcSequences'} = 'Getting data from the magnalister server.';
MLI18n::gi()->{'sModal_updatePlugin_content_copyFilesToStaging'} = 'Extracting data.';
MLI18n::gi()->{'sModal_updatePlugin_content_addIndexPhp'} = 'Extracting data.';
MLI18n::gi()->{'sModal_updatePlugin_content_finalizeUpdate'} = 'Updating Plugin.';
MLI18n::gi()->{'sModal_updatePlugin_content_afterUpdate'} = 'Preparing database.';
MLI18n::gi()->{'sModal_updatePlugin_content_success'} = 'Update completed.';
MLI18n::gi()->{'sModal_installPlugin_title'} = 'Installing magnalister plugin';
MLI18n::gi()->{'sModal_installPlugin_content_init'} = 'Downloading data from magnalister server.';
MLI18n::gi()->{'sModal_installPlugin_content_calcSequences'} = 'Downloading data from magnalister server.';
MLI18n::gi()->{'sModal_installPlugin_content_copyFilesToStaging'} = 'Extracting data.';
MLI18n::gi()->{'sModal_installPlugin_content_addIndexPhp'} = 'Extracting data.';
MLI18n::gi()->{'sModal_installPlugin_content_finalizeUpdate'} = 'Updating Plugin.';
MLI18n::gi()->{'sModal_installPlugin_content_afterUpdate'} = 'Preparing database.';
MLI18n::gi()->{'sModal_installPlugin_content_success'} = 'The initial installation of magnalister completed.';
MLI18n::gi()->{'sModal_afterUpdatePlugin_content'} = 'Updating database';
MLI18n::gi()->{'ML_TEXT_GENERIC_SAFE_MODE'} = 'The Safe Mode restriction is activated on your system. Therefore it is not possible to run updates automatically. To update magnalister manually, please download the current version from <a href="{#setting:sPublicUrl#}" title="magnalister website">magnalister website</a> and copy the directory <i>files/</i> from the unzipped archive into the root directory of your shop. Alternatively, contact your server administrator and ask for disabling the Safe Mode restriction permanently. <br /><br />If you wish, we can install the update for a small installation fee <a href="{#setting:sPublicUrl#}frontend/installation_pricing.php" title="magnalister Seite">(see prices</a>).';
MLI18n::gi()->{'sException_update_misc'} = 'The magnalister plugin cannot be updated automatically.<br/><br/>
To update magnalister manually please download the latest version from  <a href="{#setting:sPublicUrl#}" title="magnalister Seite">magnalister site</a> and copy the directory <i>files/</i> from the archive into the root directory of your shop.
We can do the manual update for you for an extra service charge if you wish (see
    <a href="{#setting:sPublicUrl#}frontend/installation_pricing.php" title="magnalister site">price list</a>).
';
MLI18n::gi()->{'sNotUpdateable_title'} = 'Update failed';
MLI18n::gi()->{'ML_ERROR_CANNOT_CONNECT_TO_SERVICE_LAYER_HEADLINE'} = 'Error during magnalister service layer request';
MLI18n::gi()->{'ML_ERROR_CANNOT_CONNECT_TO_SERVICE_LAYER_TEXT'} = 'The magnalister-Service-Layer either is not available at this moment, or your request failed. If the problem still occurs, please contact our support https://www.magnalister.com/en/contact-us/ .';
MLI18n::gi()->{'sMagnalisterRemoteServer'} = 'magnalister Server';
MLI18n::gi()->{'sUpdateError_doAgain'} = 'Click <a class="global-ajax" data-ml-global-ajax=\'{"triggerAfterSuccess":"currentUrl"}\' onclick="jqml(\'.ml-js-modalPushMessages>*\').remove();jqml(this).parent().hide();return true;" href="{#link#}">here</a> to try again.<br />
If the problem persists, please contact <a href="https://www.magnalister.com/en/contact-us/" class="ml-js-noBlockUi" target="_blank">magnalister-Service</a>.';
MLI18n::gi()->{'sException_update_notEnoughDiskSpace'} = 'Disk space full.';
MLI18n::gi()->{'sException_update_cantCreateFolder'} = 'Failed to create directory `{#path#}`.';
MLI18n::gi()->{'sException_update_insufficientFilesCount'} = 'An error occured while creating the update list.';
MLI18n::gi()->{'sException_update_wrongMethodParameter'} = 'An error occured.';
MLI18n::gi()->{'sException_update_pathNotExists'} = 'The path `{#path#}` cannot be <strong>created</b> or modified. Please change the access rights to 775 or 777.';
MLI18n::gi()->{'sException_update_pathNotWriteable'} = 'Path `{#path#}` is not writeable';
MLI18n::gi()->{'sException_update_pathNotReadable'} = 'Path `{#path#}` is not readable';
MLI18n::gi()->{'sException_update_cantDeleteFolder'} = 'Directory `{#path#}` cannot be deleted. ';
MLI18n::gi()->{'sException_update_cantCopyFile'} = 'Data `{#srcPath#}` copied to `{#dstPath#}`. ';
MLI18n::gi()->{'sException_update_cantRenameFolder'} = 'Directory `{#srcPath#}` cannot be relocated to `{#dstPath#}` because of limited writing authority. ';
MLI18n::gi()->{'sException_update_cantDeleteFile'} = 'The data `{#path#}` cannot be deleted. ';
MLI18n::gi()->{'sException_update_pathOutsideRoot'} = 'Path `{#path#}` is outside the file system. ';
MLI18n::gi()->{'installation_content_title'} = 'magnalister is installing. What\'s next?';
MLI18n::gi()->{'installation_content_freetest_url'} = 'http://www.magnalister.com/en/try-for-free/';
MLI18n::gi()->{'installation_content_firststep'} = 'Save your PassPhrase under Global Configurations (you should have received the PassPhrase via email after registration and activation).';
MLI18n::gi()->{'installation_content_notcutomer'} = 'Not a customer yet?';
MLI18n::gi()->{'installation_content_secondstep'} = 'Choose a marketplace rider to complete the configuration. <a style="pointer-events: none;">Click the info icons in configuration to get useful hints</a>';
MLI18n::gi()->{'installation_content_thirdstep'} = 'Marketplaces have many rules. Contact our support or on-screen help if you encounter problems!';
MLI18n::gi()->{'installation_content_help'} = 'Request help';
MLI18n::gi()->{'installation_content_help_url'} = 'http://www.magnalister.com/en#support';
MLI18n::gi()->{'installation_content_fourthstep'} = 'Start selling on the world\'s most important marketplaces! Please enter your PassPhrase!';
