<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sLog_timeStamp'} = 'Timestamp';
MLI18n::gi()->{'sLog_delete'} = 'Delete log entry';
MLI18n::gi()->{'aLog_ordersSync__title'} = 'Order comparison';
MLI18n::gi()->{'aLog_ordersSync__info__title'} = 'Process';
MLI18n::gi()->{'aLog_ordersSync__info__values__createOrder'} = 'New order';
MLI18n::gi()->{'aLog_ordersSync__info__values__extendOrder'} = 'Order extended';
MLI18n::gi()->{'aLog_ordersSync__marketplace'} = 'Marketplace';
MLI18n::gi()->{'aLog_ordersSync__orderno_marketplace'} = 'Order number (marketplace)';
MLI18n::gi()->{'aLog_ordersSync__orderno_shop'} = 'Order number (shop)';
MLI18n::gi()->{'aLog_ordersSync__status'} = 'Order status';
