<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'check24_prepare_form__legend__details'} = 'product details';
MLI18n::gi()->{'check24_prepare_form__legend__categories'} = 'CHECK24 categories';
MLI18n::gi()->{'check24_prepare_form__field__shippingtime__label'} = 'Shipping time';
MLI18n::gi()->{'check24_prepare_form__field__shippingtime__hint'} = '';
MLI18n::gi()->{'check24_prepare_form__field__shippingcost__label'} = 'Shipping cost';
MLI18n::gi()->{'check24_prepare_form__field__shippingcost__hint'} = '';
MLI18n::gi()->{'check24_prepare_form__field__marke__label'} = 'Brand <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__hersteller_name__label'} = 'Manufacturer: Name <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__hersteller_strasse_hausnummer__label'} = 'Manufacturer: Street Address <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__hersteller_plz__label'} = 'Manufacturer: Zip Code <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__hersteller_stadt__label'} = 'Manufacturer: City <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__hersteller_land__label'} = 'Manufacturer: State <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__hersteller_email__label'} = 'Manufacturer: E-Mail <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__hersteller_telefonnummer__label'} = 'Manufacturer: Phone';
MLI18n::gi()->{'check24_prepare_form__field__verantwortliche_person_fuer_eu_name__label'} = 'Person responsible for EU: Name <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__verantwortliche_person_fuer_eu_strasse_hausnummer__label'} = 'Person responsible for EU: Street Address <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__verantwortliche_person_fuer_eu_plz__label'} = 'Person responsible for EU: Zip Code <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__verantwortliche_person_fuer_eu_stadt__label'} = 'Person responsible for EU: City <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__verantwortliche_person_fuer_eu_land__label'} = 'Person responsible for EU: State <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__verantwortliche_person_fuer_eu_email__label'} = 'Person responsible for EU: E-Mail <span class="bull">•</span>';
MLI18n::gi()->{'check24_prepare_form__field__verantwortliche_person_fuer_eu_telefonnummer__label'} = 'Person responsible for EU: Phone';

MLI18n::gi()->add('check24_prepare_form',array(
    'legend' => array(
        'details' => 'Produktdetails',
        'categories' => 'CHECK24 Kategorien',
    ),
    'field' => array(
        'delivery' => array(
            'label' => 'Art des Versands',
            'hint' => ''
        ),
        'two_men_handling' => array(
            'label' => 'Lieferung bis zum Aufstellort',
            'hint' => 'Falls Sie kostenlos bis zum Aufstellort liefern, tragen Sie hier &quot;ja&quot; ein, sonst den Aufpreis. Wenn Sie dies nicht anbieten, lassen Sie das Feld leer.'
        ),
        'installation_service' => array(
            'label' => 'Installation des Artikels',
            'hint' => '',
            /*'values' => array (
                 '' => '-',
                 'ja' => '{#i18n:ML_BUTTON_LABEL_YES#}',
            ),*/
        ),
        'removal_old_item' => array(
            'label' => 'Mitnahme des Altger&auml;ts',
            'hint' => 'Bei Speditionsware:<br />Mitnahme des Altger&auml;ts'
        ),
        'removal_packaging' => array(
            'label' => 'Mitnahme der Verpackung',
            'hint' => 'Bei Speditionsware:<br />Mitnahme der Verpackung'
        ),
        'available_service_product_ids' => array(
            'label' => 'Zubuchbare Services',
            'hint' => 'Liste von verf&uuml;gbaren Services (Produkte-Ids aus dem Feed), die in Kombination mit dem Produkt kaufbar sind'
        ),
        'logistics_provider' => array(
            'label' => 'Logistikdienstleister',
            'hint' => 'Logistikdienstleister f&uuml;r das Produkt (z.B. DHL)'
        ),
        'custom_tariffs_number' => array(
            'label' => 'TARIC Nummer',
            'hint' => 'Die TARIC Nummer ist eine europ&auml;ische Zoll-Kennzahl f&uuml;r Waren. Wichtig wenn Sie Waren in die EU importieren, oder aus der EU ausf&uuml;hren.'
        ),
        'return_shipping_costs' => array(
            'label' => 'Kosten f&uuml;r Retoure',
            'hint' => 'Kosten f&uuml;r Retoure bei Geschmacksretouren'
        ),
    )
),false);
