<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedStatus__OK__title'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Prepared Status: Error';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Prepared Status: Open';
MLI18n::gi()->{'Check24_Productlist_Filter_aPreparedStatus__OK'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Check24_Productlist_Filter_aPreparedStatus__ERROR'} = 'Prepared Status: Error';
MLI18n::gi()->{'Check24_Productlist_Filter_aPreparedStatus__OPEN'} = 'Prepared Status: Open';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedType__Chinese'} = 'Chinese auction';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fixed price';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fixed price (CHECK24 Store)';
MLI18n::gi()->{'Check24_Productlist_Header_sPreparedType'} = 'Type of Auction';
