<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_MESSAGE_BEFORE_UPDATE_TITLE'} = 'magnalister update';
MLI18n::gi()->{'ML_MESSAGE_BEFORE_UPDATE_TEXT'} = 'The magnalister Plugin is now being updated to the newest version. This process takes 1-3 minutes.';
