<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'configform_check_entries_error'} = 'Vérifier, s\'il vous plaît, les entrées en surbrillance rouges.';
MLI18n::gi()->{'configform_quantity_value_error'} = 'Le champ "quantité" doit être un nombre décimal.';
MLI18n::gi()->{'configform_price_factor_error'} = 'Le champ majoration ou rabais doit être numérique.';
MLI18n::gi()->{'configform_price_signal_error'} = 'Vous devez donner ici  un nombre décimal.';
MLI18n::gi()->{'configform_ust_error'} = 'La TVA doit être numérique.';
MLI18n::gi()->{'configform_ust_error'} = 'La TVA doit être numérique.';
MLI18n::gi()->{'configform_quantity_value_error'} = 'Le champ "quantité" doit être un nombre décimal.';
MLI18n::gi()->{'configform_price_signal_error'} = 'Vous devez donner ici  un nombre décimal.';
MLI18n::gi()->{'configform_check_entries_error'} = 'Vérifier, s&apos;il vous plaît, les entrées en surbrillance rouges.';
MLI18n::gi()->{'configform_price_factor_error'} = 'Le champ majoration ou rabais doit être numérique.';
