<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameGuide'} = 'Aide';
MLI18n::gi()->{'sGuideContentsLink'} = 'https://www.magnalister.com/fr/#support';
MLI18n::gi()->{'sGuideContentsRootLink'} = 'https://www.magnalister.com/fr/#support';
