<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_prepare_apply_form__field__description__label'} = 'Description';
MLI18n::gi()->{'ebay_prepare_apply_form__field__description__hint'} = 'List of available placeholders for Content:
<dl>
    <dt>#TITLE#</dt>
            <dd>Product Name (Title)</dd><br>
    <dt>#ARTNR#</dt>
            <dd>Item Number in Shop</dd><br>
    <dt>#PID#</dt>
            <dd>Product ID in Shop</dd><br>
    <!--<dt>#PRICE#</dt>
            <dd>Price</dd>
    <dt>#VPE#</dt>
            <dd>Price per packing unit</dd>-->
    <dt>#SHORTDESCRIPTION#</dt>
            <dd>Short description from the Shop</dd><br>
    <dt>#DESCRIPTION#</dt>
            <dd>Description from the Shop</dd><br>
    <dt>#MOBILEDESCRIPTION#</dt>
            <dd>Short description for mobile devices (if defined)</dd><br>
    <dt>#PICTURE1#</dt>
            <dd>First product image</dd><br>
    <dt>#PICTURE2# etc.</dt>
            <dd>Second product image; with #PICTURE3#, #PICTURE4# etc, you can transfer as many pictures as you have available in your Shop.</dd><br>
    <dt>#PROPERTIES#</dt>
        <dd>A list of all product attributes. Appearance can be determined with CSS (see the code from the Standard Template)</dd>
    </dl>';
MLI18n::gi()->{'ebay_prepare_apply_form__field__description__optional__checkbox__labelNegativ'} = 'Always use product description from web-shop';
