<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Shopware_Productlist_Filter_sStatus'} = 'Statut';
MLI18n::gi()->{'Shopware_Productlist_Filter_sActive'} = 'actif';
MLI18n::gi()->{'Shopware_Productlist_Filter_sInactive'} = 'inactif';
MLI18n::gi()->{'Shopware_Productlist_Filter_sManufacturer'} = 'Fabricant';
MLI18n::gi()->{'Shopware_Productlist_Filter_sManufacturerId'} = 'Numéro de fabricant';
MLI18n::gi()->{'Shopware_Productlist_Filter_sEan'} = 'ean';
MLI18n::gi()->{'Shopware_Productlist_Filter_sCategory'} = 'Catégorie';
MLI18n::gi()->{'prepare_product_keywords'} = '<p>Seuls les recherche de mots clés sont utilisés.</p>';
