<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Shopware_Update_ClearShopwareCache'} = 'Veuillez vider le cache de votre boutique. Pour ce faire rendez-vous sur "Shopware" > "Caches / Performance" > "Vider le cache de la boutique"';
