<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Check24_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'Check24_CheckinForm__Amount'} = 'Quantité';
MLI18n::gi()->{'Check24_CheckinForm__ShippingTime'} = 'Délais de livraison (en jours)';
MLI18n::gi()->{'Check24_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'Check24_CheckinForm__SuggestedPrice'} = 'Calculé (selon les configurations)';
MLI18n::gi()->{'Check24_CheckinForm__HitPrice'} = 'Prix hit';
MLI18n::gi()->{'Check24_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'Check24_CheckinForm__SuggestedAmount'} = 'Calculé (d\'après la configuration)';
