<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameCheck24'} = 'CHECK24';
MLI18n::gi()->{'check24_inventory_listing_status'} = 'Statut';
MLI18n::gi()->ML_CHECK24_ERROR_MISSING_FIELD = 'Le champ %s est un champ obligatoire et ne doit pas être vide.';
