<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparés avec succès';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparés';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non vérifiée';
MLI18n::gi()->{'Check24_Productlist_Filter_aPreparedStatus__OK'} = 'Préparés avec succès';
MLI18n::gi()->{'Check24_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparés';
MLI18n::gi()->{'Check24_Productlist_Filter_aPreparedStatus__OPEN'} = 'Articles préparés non vérifiés';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedType__Chinese'} = 'Vente aux enchères';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Prix fixe';
MLI18n::gi()->{'Check24_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Prix fixe (boutique CHECK24)';
MLI18n::gi()->{'Check24_Productlist_Header_sPreparedType'} = 'Format de la vente';
