<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Ricardo_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparé avec succès';
MLI18n::gi()->{'Ricardo_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparé';
MLI18n::gi()->{'Ricardo_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non vérifiée';
MLI18n::gi()->{'Ricardo_Productlist_Filter_aPreparedStatus__OK'} = 'Préparé avec succès';
MLI18n::gi()->{'Ricardo_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparé';
MLI18n::gi()->{'Ricardo_Productlist_Filter_aPreparedStatus__OPEN'} = 'Préparation non vérifiée';
