<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Ricardo_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'Ricardo_CheckinForm__Amount'} = 'Quantité';
MLI18n::gi()->{'Ricardo_CheckinForm__ShippingTime'} = 'Livraison (en jours)';
MLI18n::gi()->{'Ricardo_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'Ricardo_CheckinForm__SuggestedPrice'} = 'Calculé (de la configuration)';
MLI18n::gi()->{'Ricardo_CheckinForm__HitPrice'} = 'Hit de prix';
MLI18n::gi()->{'Ricardo_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'Ricardo_CheckinForm__SuggestedAmount'} = 'Calculé (de la configuration)';
MLI18n::gi()->{'Ricardo_CheckinForm__Condition'} = 'Conditions ';
MLI18n::gi()->{'Ricardo_CheckinForm__ListingType'} = 'Type d\'annonce';
MLI18n::gi()->{'Ricardo_CheckinForm__Conditions__new'} = 'Nouveau';
MLI18n::gi()->{'Ricardo_CheckinForm__Conditions__not_specified'} = 'Non spécifié';
MLI18n::gi()->{'Ricardo_CheckinForm__Conditions__used'} = 'Utilisé';
MLI18n::gi()->{'Ricardo_CheckinForm__BuyingMode'} = 'Mode d\'achat';
MLI18n::gi()->{'Ricardo_CheckinForm__BuyingModes__buy_it_now'} = 'Achetez-le maintenant';
MLI18n::gi()->{'Ricardo_CheckinForm__BuyingModes__auction'} = 'Vente aux enchères';
MLI18n::gi()->{'Ricardo_CheckinForm__BuyingModes__classified'} = 'Classé';
MLI18n::gi()->{'Ricardo_CheckinForm__ShippingMode'} = 'Mode de livraison';
MLI18n::gi()->{'Ricardo_CheckinForm__ShippingModes__custom'} = 'Custom';
MLI18n::gi()->{'Ricardo_CheckinForm__ShippingModes__not_specified'} = 'Non spécifié';
