<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameGuide'} = 'Help';
MLI18n::gi()->{'sGuideContentsLink'} = 'https://www.magnalister.com/en/#support';
MLI18n::gi()->{'sGuideContentsRootLink'} = 'https://www.magnalister.com/en/#support';
