<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sAmazon_automatically'} = '-- allocate automatically --';
MLI18n::gi()->set('sAmazon_product_bolletpoints_fieldName', 'short description', true);
MLI18n::gi()->{'amazon_prepare_apply_form__field__keywords__help'} = '
<h3>Optimize product ranking with Amazon keywords</h3>
<br>
General keywords are used to optimize the ranking and for better filterability on Amazon. They are stored with the product invisibly, when uploaded.
<br><br>
<h2>Options for the Submission of General Keywords</h2>

1. Always use up-to-date keywords from the web shop (SEO keywords): 
<br><br>
Here, the keywords are taken from the SEO keywords field of the corresponding product in the web shop and submitted to Amazon.
<br><br>
2. Manually enter general keywords in magnalister 
<br><br>
If you do not want to use the SEO keywords stored in the web shop product, you can enter your own keywords in the empty text field provided by magnalister.
<br><br>
<b>Important Notes:</b>
<ul><li>
If you enter keywords manually, separate them with a space (not a comma!). The maximum length of all keywords (rule of thumb: 1 character = 1 byte. Exception: special characters such as Ä, Ö, Ü = 2 bytes) may not exceed 250 bytes.
</li><li>
If the keywords of your web shop product are separated by commas, magnalister automatically converts these commas into spaces when uploading the product. The limitation to 250 bytes also applies here.
</li><li>
If the allowed byte count is exceeded, Amazon may return an error message after the product upload, which can be viewed in the magnalister error log. Please note that it can take up to 60 minutes until error messages are displayed in the magnalister error log.
</li><li>
Submission of Platinum Keywords: Transfer of Platinum Keywords: If you are an Amazon Platinum seller, please inform the magnalister support about it. We will then activate the submission of Platinum keywords. magnalister uses the general keywords and adopts them 1:1. General keywords and Platinum keywords are therefore identical.
</li><li>
If you want to transfer Platinum keywords to Amazon that differ from the "General Keywords", use the magnalister attribute matching under "Prepare Items" -> "Create New Products" -> "Amazon Optional Attributes". To do so, select "Platinum keywords 1-5" from the list of available Amazon attributes and match the corresponding web shop attribute.
</li><li>
In addition to general keywords, there are other Amazon-relevant keywords (e.g. thesaurus attribute keywords, target group keywords or topic keywords), which you can also be submitted to Amazon via attribute matching.
</li></ul>
';
MLI18n::gi()->{'amazon_prepare_apply_form__field__keywords__optional__checkbox__labelNegativ'} = 'Always use the Keywords from the shop (SEO Keywords)';
