<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2021 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameConfiguration'} = 'Configuration générale';
MLI18n::gi()->{'sChangeKeyAlert'} = '<div id="switchSKU" title="{#i18n:ML_TEXT_CONFIRM_SKU_CHANGE_TITLE#}">{#i18n:ML_TEXT_CONFIRM_SKU_CHANGE_TEXT#}</div>';
MLI18n::gi()->{'sWarningGlobalConfigurationIsNotConfigured'} = 'Pour poursuivre, veuillez d’abord procéder à la configuration générale et la sauvegarder.';