<?php
/**
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2019 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Googleshopping_Productlist_Cell_aPreparedStatus__OK__title'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Googleshopping_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Prepared Status: Error';
MLI18n::gi()->{'Googleshopping_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Prepared Status: Open';
MLI18n::gi()->{'Googleshopping_Productlist_Filter_aPreparedStatus__OK'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Googleshopping_Productlist_Filter_aPreparedStatus__ERROR'} = 'Prepared Status: Error';
MLI18n::gi()->{'Googleshopping_Productlist_Filter_aPreparedStatus__OPEN'} = 'Prepared Status: Open';
MLI18n::gi()->{'Googleshopping_Productlist_Cell_aPreparedType__Chinese'} = 'Chinese auction';
MLI18n::gi()->{'Googleshopping_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fixed price';
MLI18n::gi()->{'Googleshopping_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fixed price (Google Shopping Store)';
MLI18n::gi()->{'Googleshopping_Productlist_Header_sPreparedType'} = 'Type of Auction';
