<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2022 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'form_config_orderimport_shop_lable'} = 'Shop Client';
MLI18n::gi()->{'form_config_orderimport_shop_help'} = 'Determine which Client Shop orders should be sorted into.';
MLI18n::gi()->{'form_config_orderimport_imagesize_lable'} = 'Image size';
MLI18n::gi()->{'form_config_orderimport_imagesize_help'} = '<p>Please enter the pixel width for the image as should appear on the Marketplace. The height will be automatically matched based on the original aspect ratio.</p>
<p>The source files will be processed from the image folder {#setting:sSourceImagePath#}, and will be stored in the folder {#setting:sImagePath#} with the selected pixel width for use on the Marketplace.</p>';
MLI18n::gi()->{'form_config_orderimport_imagesize_hint'} = 'Saved under: {#setting:sImagePath#}';
MLI18n::gi()->{'form_config_send_mailcontentcontailner_testmail'} = 'TESTMAIL';

MLI18n::gi()->form_orderimport_paymentandshipping_values_textfield_title = 'From text-field';