<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2022 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEbay'} = 'eBay';
MLI18n::gi()->{'sEbayNoInternationalShipping'} = 'No shipping abroad';
MLI18n::gi()->{'sEbayProductIdentifierSyncButton'} = 'Synchronization of EAN and MPN to eBay';
MLI18n::gi()->{'sEbayCacheAPICalls'} = 'Refresh API magnalister Calls Cache';
MLI18n::gi()->{'sEbaySyncButtonDisableIfno'} = 'This functionality is not yet available.';
MLI18n::gi()->{'sEbayDefaultValueText'} = 'default';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_ITEMS'} = 'Price and Stock Synchronization';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_PRODUCTDETAILUPDATES'} = 'eBay mandatory Product Detail Data:';
MLI18n::gi()->{'ML_EBAY_PLUS_ORDER'} = 'This is an <span style="color:#e31a1c;">eBay Plus</span> order.';
MLI18n::gi()->{'ML_TEXT_WARNING'} = 'Warning';
MLI18n::gi()->{'ML_EBAY_PLUS_ORDER_WRONG_SHIPPING'} = 'The selected shipping method is not allowed for eBay Plus.';
MLI18n::gi()->{'eBaySalesRecordNumber'} = 'Sales Record Number';
MLI18n::gi()->{'ebay_order_detail_information_to_ebay_seller_hub'} = '<br>Click on this <a href="%s">link</a> to process the (partial) order refund via the eBay Seller Hub.';
MLI18n::gi()->ML_EBAY_NO_BASEPRICE_FOR_VARIATIONS_WITH_DIFFERENT_BASEPRICE = 'eBay does not support base prices for variants.<br>Since the base price is different on your variants, we have removed the base prices for the item (SKU: {#SKU#}).';
MLI18n::gi()->ML_EBAY_IMPORT_CATEGORIES = 'eBay Category Import';
MLI18n::gi()->ML_EBAY_TAX_BY_EBAY = 'Tax/VAT handled by eBay';
