<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Ebay_CheckinForm__Price'} = 'Price';
MLI18n::gi()->{'Ebay_CheckinForm__Amount'} = 'Number';
MLI18n::gi()->{'Ebay_CheckinForm__ShippingTime'} = 'Shipping time (in days)';
MLI18n::gi()->{'Ebay_CheckinForm__ShopPrice'} = 'Shop';
MLI18n::gi()->{'Ebay_CheckinForm__SuggestedPrice'} = 'Calculated (acc. to Configuration)';
MLI18n::gi()->{'Ebay_CheckinForm__HitPrice'} = 'Price Hit';
MLI18n::gi()->{'Ebay_CheckinForm__AvailibleAmount'} = 'Available';
MLI18n::gi()->{'Ebay_CheckinForm__SuggestedAmount'} = 'Calculated (acc. to Configuration)';
