<?php
/* Autogenerated file. Do not change! */

/*MLI18n::gi()->{'Ebay_listings_popup_after_addItem_content'} = '<b>Note about processing time and activation:</b>
<br /><br />
Processing can just take a few seconds or up to 6 hours.
<br /><br />
Articles not requiring eBay catalog matching: eBay needs 5-10 seconds to process each article (incl. image package).
<br /><br />
eBay catalog articles (requiring ePID): Processing time and testing can take eBay 4-6 hours, especially when a new product is suggested for eBay’s catalog (happens automatically).
<br /><br />
You can always check the processing status via the inventory tab. Possible error reports after processing will be shown in the “error log” tab.';*/
MLI18n::gi()->{'Ebay_listings_popup_after_addItem_content'} = '<b>Note about processing time and activation:</b><br /><br />Processing takes several seconds per item.<br /><br />eBay needs 5-10 seconds to process each item. If using the image package, add the same time per image.<br /><br />The data are uploaded to our servers, and then from there to eBay.<br /><br />You can always check the processing status via the inventory tab. Possible error reports after processing will be shown in the &quot;error log&quot; tab.';
MLI18n::gi()->{'Ebay_listings_status__pending'} = 'In waiting queue';
MLI18n::gi()->{'Ebay_listings_status__active'} = 'Currently in the inventory';
MLI18n::gi()->{'Ebay_listings_status__pending_process'} = 'Item will be updated';
MLI18n::gi()->{'Ebay_listings_status__waiting_catalog'} = 'Product is in Review on eBay';
MLI18n::gi()->{'Ebay_listings_status__est_until'} = 'approx. until';
MLI18n::gi()->{'Ebay_listings_status__not_yet_known'} = 'not yet known';
MLI18n::gi()->{'Ebay_listings_prepareType__matched'} = 'manually matched';
MLI18n::gi()->{'Ebay_listings_prepareType__automatched'} = 'auto-matched';
MLI18n::gi()->{'Ebay_listings_prepareType__applied'} = 'manually applied';
MLI18n::gi()->{'Ebay_listings_prepareType__autoapplied'} = 'auto-applied';
MLI18n::gi()->{'Ebay_listings_prepareType__notMatched'} = 'Own data<br/><span class="small">(catalog matching not required)</span>';
MLI18n::gi()->{'sEbayErrorLast5Minute'} = 'eBay has returned error messages in the last 5 minutes. Please check the Error Log';
