<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Ebay_Product_Matching'} = 'Product Matching';
MLI18n::gi()->{'Ebay_Productlist_Match_Manual_Button_Save'} = 'Save matchingand prepare Item';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Select'} = 'Select';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Title'} = 'eBay Title';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_SkuOfManufacturer'} = 'MPN';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Barcode'} = 'Bar code (UPC, EAN or ISBN)';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Epid'} = 'ePID';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Search_Free'} = 'New Search';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_Search_EPID'} = 'ePID search';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_CreateNewProduct'} = 'Apply new Product in eBay Catalog';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_DontMatch'} = 'Don\'t match';
MLI18n::gi()->{'Ebay_Productlist_Itemsearch_DontMatch_Warning'} = 'Variants are transmitted to eBay even if you choose “don’t match.” Please note the following differences:
<br />
<ol><li>An UPC/EAN code is stored in the product variant in your online shop
<br /><br />
In this case, magnalister tries to match an appropriate product from the eBay catalog via UPC/EAN. If this process is successful, the variant is linked with an ePID and will be published on eBay.
<br /><br />
If no product from the catalog can definitely be matched via EAN, magnalister automatically requests the variant to be included in the eBay catalog. Once eBay approves the variant, it is automatically published on the marketplace.</li><br />
<li>No UPC/EAN code stored in the product variant
<br /><br />
In this case, product matching with the eBay catalog was not possible and eBay gives you an error message. You will find these messages in the “Inventory” tab under “Error Log.”</li></ol>';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedStatus__OK__title'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Prepared Status: Error';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Prepared Status: Open';
MLI18n::gi()->{'Ebay_Productlist_Filter_aPreparedStatus__OK'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Ebay_Productlist_Filter_aPreparedStatus__ERROR'} = 'Prepared Status: Error';
MLI18n::gi()->{'Productlist_Filter_aMarketplaceSync__notTransferred'} = 'Display as not transferred to {#marketplace#} within the last year ***';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__Matched'} = 'ePID product<br /><span class="small">(catalog matching required)</span>';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__NotMatched'} = 'Own data<br /><span class="small">(catalog matching not required)</span>
';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__Chinese'} = 'Chinese auction';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fixed price';
MLI18n::gi()->{'Ebay_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fixed price (eBay store)';
MLI18n::gi()->{'Ebay_Productlist_Header_sPreparedListingType'} = 'Type of Auction';
MLI18n::gi()->{'Ebay_Productlist_Header_sPreparedType'} = 'Type of Preparation';
MLI18n::gi()->{'Ebay_Productlist_Prepare_sResetValuesButton'} = 'Reset (parts of) Item Preparation';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__buttons__ok'} = 'ok';
MLI18n::gi()->{'Ebay_Productlist_Prepare_aResetValues__buttons__abort'} = 'cancel';
MLI18n::gi()->{'Productlist_Prepare_aResetValues__checkboxes__reset_strikeprices__label'} = 'Delete Strikethrough Prices';
MLI18n::gi()->{'Ebay_Productlist_Matching_aResetValues__buttons__ok'} = 'ok';
MLI18n::gi()->{'Ebay_Productlist_Matching_aResetValues__buttons__abort'} = 'cancel';
MLI18n::gi()->{'Ebay_Productlist_Matching_aResetValues__checkboxes__matching'} = 'Remove matching';
MLI18n::gi()->{'Ebay_Productlist_Matching_aResetValues__checkboxes__unprepare'} = 'Completely remove preparation';
MLI18n::gi()->{'Ebay_Productlist_Upload_ShippingFee_Notice_Title'} = 'Information';
MLI18n::gi()->{'Ebay_Productlist_Upload_ShippingFee_Notice_Content'} = 'Depending on your eBay plan, eBay may charge fees per listing per product.
To avoid unintended charges, please check your eBay plan.';
