<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Orderimport_CurrencyCodeDontExistsError'} = 'The market-place order-number {#mpOrderId#} needs the currency {#ISO#} in your web-shop configuration to be able to import the order.';
