<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_GENERIC_QTY'} = 'Qty';
MLI18n::gi()->{'ML_GENERIC_ITEM'} = 'Item';
MLI18n::gi()->{'ML_GENERIC_EACH'} = 'Each';
MLI18n::gi()->{'ML_GENERIC_TOTAL'} = 'Total';
