<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sInventorySyncByService'} = 'Price and Stock has been synchronized for the following market places';
MLI18n::gi()->{'sOrderStatusSyncByService'} = 'Order-status will be synchronized for the following marketplaces:';
MLI18n::gi()->{'sAddItemProductWithZeroQuantity'} = 'Items with 0 stock will be omitted. ';
