<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Amazon_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'Amazon_CheckinForm__Amount'} = 'Quantité';
MLI18n::gi()->{'Amazon_CheckinForm__ShippingTime'} = 'Délai de traitement (en jours)';
MLI18n::gi()->{'Amazon_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'Amazon_CheckinForm__SuggestedPrice'} = 'Calculées (de la configuration)';
MLI18n::gi()->{'Amazon_CheckinForm__HitPrice'} = 'Meilleur prix';
MLI18n::gi()->{'Amazon_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'Amazon_CheckinForm__SuggestedAmount'} = 'Calculé (d\'après la configuration)';
