<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Hood_listings_popup_after_addItem_content'} = '';
MLI18n::gi()->{'Hood_listings_status__pending'} = 'In waiting queue';
MLI18n::gi()->{'Hood_listings_status__active'} = 'Currently in the inventory';
MLI18n::gi()->{'Hood_listings_status__pending_process'} = 'Article will be updated';
