<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_ERROR_GLOBAL'} = 'Une erreur est survenue.
Veuillez réessayer ultérieurement. Si l\'erreur continue à se produire, veuillez contacter notre équipe de support  https://www.magnalister.com/fr/contactez-nous/ .';
MLI18n::gi()->{'ML_ERROR_GLOBAL'} = 'Une erreur est survenue.
Veuillez réessayer ultérieurement. Si l&apos;erreur continue à se produire, veuillez contacter notre équipe de support  {#setting:MAGNA_SUPPORT_URL#}.';
