<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sLog_timeStamp'} = 'Durée';
MLI18n::gi()->{'sLog_delete'} = 'Supprimez l\'inscription Log';
MLI18n::gi()->{'aLog_ordersSync__title'} = 'Comparaison des commandes';
MLI18n::gi()->{'aLog_ordersSync__info__title'} = 'Processus';
MLI18n::gi()->{'aLog_ordersSync__info__values__createOrder'} = 'Nouvelle commande';
MLI18n::gi()->{'aLog_ordersSync__info__values__extendOrder'} = 'Prolongez les commandes';
MLI18n::gi()->{'aLog_ordersSync__marketplace'} = 'Place de marché';
MLI18n::gi()->{'aLog_ordersSync__orderno_marketplace'} = 'Numéro de commande (place de marché)';
MLI18n::gi()->{'aLog_ordersSync__orderno_shop'} = 'Numéro de commande (boutique)';
MLI18n::gi()->{'aLog_ordersSync__status'} = 'Statut de la commande';
MLI18n::gi()->{'sLog_timeStamp'} = 'Durée';
MLI18n::gi()->{'aLog_ordersSync__info__title'} = 'Processus';
MLI18n::gi()->{'aLog_ordersSync__status'} = 'Statut de la commande';
MLI18n::gi()->{'aLog_ordersSync__orderno_shop'} = 'Numéro de commande (boutique)';
MLI18n::gi()->{'aLog_ordersSync__orderno_marketplace'} = 'Numéro de commande (place de marché)';
MLI18n::gi()->{'aLog_ordersSync__info__values__extendOrder'} = 'Prolongez les commandes';
MLI18n::gi()->{'aLog_ordersSync__title'} = 'Comparaison des commandes';
MLI18n::gi()->{'aLog_ordersSync__info__values__createOrder'} = 'Nouvelle commande';
MLI18n::gi()->{'aLog_ordersSync__marketplace'} = 'Place de marché';
MLI18n::gi()->{'sLog_delete'} = 'Supprimez l&apos;inscription Log';
