<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'priceminister_prepare_match_manual__legend__unit'} = 'Global settings';
MLI18n::gi()->{'priceminister_prepare_match_manual__legend__manualmatching'} = 'Matching';
MLI18n::gi()->{'priceminister_prepare_match_manual__legend__variationmatching__0'} = '{#i18n:attributes_matching_required_attributes#}';
MLI18n::gi()->{'priceminister_prepare_match_manual__legend__variationmatching__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'priceminister_prepare_match_manual__legend__subcategories'} = 'priceminister_prepare_match_manual__legend__subcategories';
MLI18n::gi()->{'priceminister_prepare_match_manual__legend__variationmatchingoptional__0'} = '{#i18n:attributes_matching_optional_attributes#}';
MLI18n::gi()->{'priceminister_prepare_match_manual__legend__variationmatchingoptional__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'priceminister_prepare_match_manual__field__itemcondition__label'} = 'Condition';
MLI18n::gi()->{'priceminister_prepare_match_manual__field__comment__label'} = 'Notes about your product';
MLI18n::gi()->{'priceminister_prepare_match_manual__field__webshopattribute__label'} = 'We Shop Attribute';
MLI18n::gi()->{'form_action_prepare_and_next'} = 'Save and continue';
MLI18n::gi()->{'priceminister_label_product_at_priceminister'} = 'Product on PriceMinister';
MLI18n::gi()->{'priceminister_not_matched_category'} = 'In order to perform product matching for selected products, please first match category attributes in "Variation Matching" tab for following categories:';
MLI18n::gi()->{'priceminister_prepare_match_manual__field__attributematching__matching__titlesrc'} = 'Shop Value';
MLI18n::gi()->{'priceminister_prepare_match_manual__field__attributematching__matching__titledst'} = 'PriceMinister Value';