<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'PriceMinister_CheckinForm__Price'} = 'Price';
MLI18n::gi()->{'PriceMinister_CheckinForm__Amount'} = 'Quantity';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShippingTime'} = 'Shipping Time (Days)';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShopPrice'} = 'Shop';
MLI18n::gi()->{'PriceMinister_CheckinForm__SuggestedPrice'} = 'Calculated (as configured)';
MLI18n::gi()->{'PriceMinister_CheckinForm__HitPrice'} = 'Price hit';
MLI18n::gi()->{'PriceMinister_CheckinForm__AvailibleAmount'} = 'Available';
MLI18n::gi()->{'PriceMinister_CheckinForm__SuggestedAmount'} = 'Calculated (as configured)';
MLI18n::gi()->{'PriceMinister_CheckinForm__Condition'} = 'Item condition';
MLI18n::gi()->{'PriceMinister_CheckinForm__ListingType'} = 'Listing type';
MLI18n::gi()->{'PriceMinister_CheckinForm__Conditions__new'} = 'New';
MLI18n::gi()->{'PriceMinister_CheckinForm__Conditions__not_specified'} = 'Not specified';
MLI18n::gi()->{'PriceMinister_CheckinForm__Conditions__used'} = 'Used';
MLI18n::gi()->{'PriceMinister_CheckinForm__BuyingMode'} = 'Buying mode';
MLI18n::gi()->{'PriceMinister_CheckinForm__BuyingModes__buy_it_now'} = 'Buy it now';
MLI18n::gi()->{'PriceMinister_CheckinForm__BuyingModes__auction'} = 'Auction';
MLI18n::gi()->{'PriceMinister_CheckinForm__BuyingModes__classified'} = 'Classified';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShippingMode'} = 'Shipping mode';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShippingModes__custom'} = 'Custom';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShippingModes__not_specified'} = 'Not specified';
