<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNamePriceMinister'} = 'PriceMinister';
MLI18n::gi()->{'ML_PRICEMINISTER_TEXT_NO_MATCHED_PRODUCTS'} = 'No items have been prepared for PriceMinister yet. You can prepare items by selecting the "Product Prepare" tab.<br>
If you miss some products you already have prepared, please check whether the products have active status, and if not, whether the configuration allows to upload inactive iems.';
MLI18n::gi()->{'priceminister_upload_explanation'} = 'Uploaded products will usually be listed within one hour on PriceMinister. Articles can be found in your PriceMinister Seller Account after that time.';
MLI18n::gi()->{'priceminister_pre_upload_popup'} = 'PriceMinister limits the article quantity to 20,000 per merchant. <br> Would you like to upload or cancel and select the products again new?';
MLI18n::gi()->{'priceminister_label_not_matched'} = 'do not match';
MLI18n::gi()->{'priceminister_label_title'} = 'Priceminister Title';
MLI18n::gi()->{'priceminister_category'} = 'Priceminister Category';
MLI18n::gi()->{'priceminister_label_item_id'} = 'PriceMinister Item ID';
MLI18n::gi()->{'priceminister_search_by_keywords'} = 'Search by keywords';
MLI18n::gi()->{'priceminister_search_by_ean'} = 'Search by EAN';
MLI18n::gi()->{'priceminister_search_by_category'} = 'Search by Category';
MLI18n::gi()->{'priceminister_search_by_pm_productid'} = 'Search by PriceMinister productId';
