<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_SKU'} = 'SKU';
MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_NAME'} = 'PriceMinister Title';
MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_SHOP_PREIS'} = 'PriceMinister Price';
MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_MARKETPLACE_PREIS'} = 'Marketplace Price';
MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_MARKETPLACE_QUANTITY'} = 'Stock: Shop / PriceMinister';
MLI18n::gi()->{'priceminister_inventory_listing_status'} = 'Status';
MLI18n::gi()->{'priceminister_inventory_is_split'} = 'priceminister_inventory_is_split';
MLI18n::gi()->{'priceminister_inventory_reject_message'} = 'Please contact the PriceMinister Support and ask for the reason why the product could not be listed.';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedStatus__OK__title'} = 'Successfully prepared';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Faultly prepared';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Prepared not checked';
MLI18n::gi()->{'Priceminister_Productlist_Filter_aPreparedStatus__OK'} = 'Successfully prepared';
MLI18n::gi()->{'Priceminister_Productlist_Filter_aPreparedStatus__ERROR'} = 'Faultly prepared';
MLI18n::gi()->{'Priceminister_Productlist_Filter_aPreparedStatus__OPEN'} = 'Prepared not checked';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__Chinese'} = 'Auction (Chinese)';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fix price';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fix price (PriceMinister Store)';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__manual'} = 'Manual matching';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__auto'} = 'Automatic matching';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__apply'} = 'Create new products';
MLI18n::gi()->{'Priceminister_Productlist_Header_sPreparedType'} = 'preparation type';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Manual_Title_Single'} = 'Single Matching';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Manual_Title_Multi'} = 'Multi Matching';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Title'} = 'Automatic matching';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Summary'} = '%d articles successfully matched  <br/><br/>
%d articles could not be matched .<br/>
%d articles with multiple outcome.';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Summary_Categories'} = '<br/>You need to match this categories: %s.';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Manual_Desc'} = 'Try to match the EAN and title with articles on PriceMinister for shop-articles selected from the checkbox.<br/ ><br/ >
You receive a detailed result for successful and unsuccessful search and can individually select which hit should be used for matching.<br/ ><br/ >
Processing is very effective but also time-consuming.';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Desc'} = 'Checkbox-selected shop articles are processed automatically in the background:
The article will be matched automatically to an existing PriceMinister EAN with the assigned article-EAN .<br/ ><br/ >
Care of EAN numbers for each article is therefore required.';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Confirm'} = 'Please note that automatic matching only effects via EAN check. It is possible that PriceMinister articles with description or pictures of lower quality will be matched. Because of that reason matching can result in a worse result than the manual matching.<br/ ><br/ >
RedGecko GmbH does not take liabilty for accuracy of matched products.';
