<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Hitmeister_CheckinForm__Price'} = 'Price';
MLI18n::gi()->{'Hitmeister_CheckinForm__Amount'} = 'Quantity';
MLI18n::gi()->{'Hitmeister_CheckinForm__HandlingTime'} = 'Handling time (in days)';
MLI18n::gi()->{'Hitmeister_CheckinForm__ShopPrice'} = 'Shop';
MLI18n::gi()->{'Hitmeister_CheckinForm__SuggestedPrice'} = 'Calculated (acc. to Configuration)';
MLI18n::gi()->{'Hitmeister_CheckinForm__HitPrice'} = 'Preis-Hit';
MLI18n::gi()->{'Hitmeister_CheckinForm__AvailibleAmount'} = 'Available';
MLI18n::gi()->{'Hitmeister_CheckinForm__SuggestedAmount'} = 'Calculated (acc. to Configuration)';
MLI18n::gi()->{'Hitmeister_CheckinForm__Condition'} = 'Item condition';
MLI18n::gi()->{'Hitmeister_CheckinForm__ListingType'} = 'Listing type';
MLI18n::gi()->{'Hitmeister_CheckinForm__Conditions__new'} = 'New';
MLI18n::gi()->{'Hitmeister_CheckinForm__Conditions__not_specified'} = 'Not specified';
MLI18n::gi()->{'Hitmeister_CheckinForm__Conditions__used'} = 'Used';
MLI18n::gi()->{'Hitmeister_CheckinForm__BuyingMode'} = 'Buying mode';
MLI18n::gi()->{'Hitmeister_CheckinForm__BuyingModes__buy_it_now'} = 'Buy it now';
MLI18n::gi()->{'Hitmeister_CheckinForm__BuyingModes__auction'} = 'Auction';
MLI18n::gi()->{'Hitmeister_CheckinForm__BuyingModes__classified'} = 'Classified';
MLI18n::gi()->{'Hitmeister_CheckinForm__ShippingMode'} = 'Shipping mode';
MLI18n::gi()->{'Hitmeister_CheckinForm__ShippingModes__custom'} = 'Custom';
MLI18n::gi()->{'Hitmeister_CheckinForm__ShippingModes__not_specified'} = 'Not specified';
