<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2024 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_prepare_match_manual__legend__unit'} = 'Unit attributes';
MLI18n::gi()->{'hitmeister_prepare_match_manual__legend__manualmatching'} = 'Matching';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__itemcondition__label'} = 'Condition';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__handlingtime__label'} = 'Handling Time';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__itemcountry__label'} = 'Article is sent from';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__shippinggroup__label'} = 'Shipping Group';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__comment__label'} = 'Hint to your article';
MLI18n::gi()->{'form_action_prepare_and_next'} = 'Save and Next';
MLI18n::gi()->{'hitmeister_label_product_at_hitmeister'} = 'Item on Kaufland';
