<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2024 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_prepare_form__legend__language'} = 'hitmeister_prepare_form__legend__language';
MLI18n::gi()->{'hitmeister_prepare_form__legend__details'} = 'hitmeister_prepare_form__legend__details';
MLI18n::gi()->{'hitmeister_prepare_form__legend__templates'} = 'hitmeister_prepare_form__legend__templates';
MLI18n::gi()->{'hitmeister_prepare_form__legend__categories'} = 'hitmeister_prepare_form__legend__categories';
MLI18n::gi()->{'hitmeister_prepare_form__legend__price'} = 'hitmeister_prepare_form__legend__price';
MLI18n::gi()->{'hitmeister_prepare_form__legend__shipping'} = 'hitmeister_prepare_form__legend__shipping';
MLI18n::gi()->{'hitmeister_prepare_form__legend__promotion'} = 'Promotion';
MLI18n::gi()->{'hitmeister_prepare_form__legend__other'} = 'hitmeister_prepare_form__legend__other';
MLI18n::gi()->{'hitmeister_prepare_form__field__categories__label'} = 'Kaufland Categories';
MLI18n::gi()->{'hitmeister_prepare_form__field__primarycategory__label'} = 'hitmeister_prepare_form__field__primarycategory__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__articlecondition__label'} = 'Item Condition';
MLI18n::gi()->{'hitmeister_prepare_form__field__listinglangs__label'} = 'hitmeister_prepare_form__field__listinglangs__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__langde__label'} = 'DE';
MLI18n::gi()->{'hitmeister_prepare_form__field__langfr__label'} = 'FR';
MLI18n::gi()->{'hitmeister_prepare_form__field__detitle__label'} = 'Title (German)';
MLI18n::gi()->{'hitmeister_prepare_form__field__detitle__hint'} = 'Title max. 40 characters <br> Placeholders allowed: <br> #BASEPRICE# - Price per Unit';
MLI18n::gi()->{'hitmeister_prepare_form__field__detitle__optional__checkbox__labelNegativ'} = 'Always use product title from web-shop';
MLI18n::gi()->{'hitmeister_prepare_form__field__desubtitle__label'} = 'Subtitle (German)';
MLI18n::gi()->{'hitmeister_prepare_form__field__desubtitle__hint'} = 'hitmeister_prepare_form__field__desubtitle__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__desubtitle__optional__select__false'} = 'hitmeister_prepare_form__field__desubtitle__optional__select__false';
MLI18n::gi()->{'hitmeister_prepare_form__field__desubtitle__optional__select__true'} = 'hitmeister_prepare_form__field__desubtitle__optional__select__true';
MLI18n::gi()->{'hitmeister_prepare_form__field__dedescription__label'} = 'Description (German)';
MLI18n::gi()->{'hitmeister_prepare_form__field__dedescription__hint'} = 'List of available place holders for product description:<dl><dt>#TITLE#</dt><dd>Product name (Titel)</dd><dt>#ARTNR#</dt><dd>Article number from the shop</dd><dt>#PID#</dt><dd>Products ID</dd><!--<dt>#PRICE#</dt><dd>Price</dd><dt>#VPE#</dt><dd>Price per packaging unit</dd>--><dt>#SHORTDESCRIPTION#</dt><dd>Short Description from Shop</dd><dt>#DESCRIPTION#</dt><dd>Description from Shop</dd><dt>#WEIGHT#</dt><dd>Products weight</dd><dt>#PICTURE1#</dt><dd>First Product-Image</dd><dt>#PICTURE2# etc.</dt><dd>Second Product-Image; with #PICTURE3#, #PICTURE4# etc. More Images can be sent, as many as available in the shop.</dd></dl>';
MLI18n::gi()->{'hitmeister_prepare_form__field__dedescription__optional__checkbox__labelNegativ'} = 'Always use product description from web-shop';
MLI18n::gi()->{'hitmeister_prepare_form__field__frtitle__label'} = 'Title (French)';
MLI18n::gi()->{'hitmeister_prepare_form__field__frtitle__hint'} = 'Title max. 40 characters <br> Placeholders allowed: <br> #BASEPRICE# - Price per Unit';
MLI18n::gi()->{'hitmeister_prepare_form__field__frtitle__optional__checkbox__labelNegativ'} = 'Always use product title from web-shop';
MLI18n::gi()->{'hitmeister_prepare_form__field__frsubtitle__label'} = 'Subtitle (French)';
MLI18n::gi()->{'hitmeister_prepare_form__field__frsubtitle__hint'} = 'hitmeister_prepare_form__field__frsubtitle__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__frsubtitle__optional__select__false'} = 'hitmeister_prepare_form__field__frsubtitle__optional__select__false';
MLI18n::gi()->{'hitmeister_prepare_form__field__frsubtitle__optional__select__true'} = 'hitmeister_prepare_form__field__frsubtitle__optional__select__true';
MLI18n::gi()->{'hitmeister_prepare_form__field__frdescription__label'} = 'Description (French)';
MLI18n::gi()->{'hitmeister_prepare_form__field__frdescription__hint'} = 'List of available place holders for product description:<dl><dt>#TITLE#</dt><dd>Product name (Titel)</dd><dt>#ARTNR#</dt><dd>Article number from the shop</dd><dt>#PID#</dt><dd>Products ID</dd><!--<dt>#PRICE#</dt><dd>Price</dd><dt>#VPE#</dt><dd>Price per packaging unit</dd>--><dt>#SHORTDESCRIPTION#</dt><dd>Short Description from Shop</dd><dt>#DESCRIPTION#</dt><dd>Description from Shop</dd><dt>#WEIGHT#</dt><dd>Products weight</dd><dt>#PICTURE1#</dt><dd>First Product-Image</dd><dt>#PICTURE2# etc.</dt><dd>Second Product-Image; with #PICTURE3#, #PICTURE4# etc. More Images can be sent, as many as available in the shop.</dd></dl>';
MLI18n::gi()->{'hitmeister_prepare_form__field__frdescription__optional__checkbox__labelNegativ'} = 'Always use product description from web-shop';
MLI18n::gi()->{'hitmeister_prepare_form__field__images__label'} = 'Product images';
MLI18n::gi()->{'hitmeister_prepare_form__field__images__hint'} = 'hitmeister_prepare_form__field__images__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__descriptiontemplate__label'} = 'hitmeister_prepare_form__field__descriptiontemplate__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__warranty__label'} = 'hitmeister_prepare_form__field__warranty__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__warrantycondition__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__warrantyconditionajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__warrantydescription__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__buyingmode__label'} = 'hitmeister_prepare_form__field__buyingmode__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__buyingmode__hint'} = 'hitmeister_prepare_form__field__buyingmode__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__price__label'} = 'hitmeister_prepare_form__field__price__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__fixpriceajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__fixprice__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enablebuynowpriceajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enablebuynowpriceajax__valuehint'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enablebuynowprice__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enablebuynowprice__valuehint'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__auction__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__priceajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__priceforauction__label'} = 'hitmeister_prepare_form__field__priceforauction__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__priceincrement__label'} = 'hitmeister_prepare_form__field__priceincrement__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__durationcontainer__label'} = 'hitmeister_prepare_form__field__durationcontainer__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__durationcontainer__hint'} = 'Duration of Auction';
MLI18n::gi()->{'hitmeister_prepare_form__field__duration__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__startdate__label'} = 'hitmeister_prepare_form__field__startdate__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__endtime__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enddate__label'} = 'hitmeister_prepare_form__field__enddate__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__maxrelistcountcontainer__label'} = 'hitmeister_prepare_form__field__maxrelistcountcontainer__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__maxrelistcount__label'} = 'hitmeister_prepare_form__field__maxrelistcount__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__payment__label'} = 'Payment';
MLI18n::gi()->{'hitmeister_prepare_form__field__payment__hint'} = 'Accepted payment methods';
MLI18n::gi()->{'hitmeister_prepare_form__field__paymentmethods__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__paymentmethodsajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__paymentdescription__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__delivery__label'} = 'hitmeister_prepare_form__field__delivery__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliverycondition__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliveryconditionajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliverypackage__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliverydescription__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliverycost__label'} = 'Shipping costs';
MLI18n::gi()->{'hitmeister_prepare_form__field__availabilitycontainer__label'} = 'hitmeister_prepare_form__field__availabilitycontainer__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__availability__label'} = 'hitmeister_prepare_form__field__availability__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__promotion__label'} = 'hitmeister_prepare_form__field__promotion__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__firstpromotion__label'} = 'hitmeister_prepare_form__field__firstpromotion__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__firstpromotion__hint'} = 'hitmeister_prepare_form__field__firstpromotion__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__secondpromotion__label'} = 'hitmeister_prepare_form__field__secondpromotion__label';
MLI18n::gi()->{'hitmeister_prepare_form__field__secondpromotion__hint'} = 'hitmeister_prepare_form__field__secondpromotion__hint';
MLI18n::gi()->{'hitmeister_prepareform_max_length_part1'} = 'hitmeister_prepareform_max_length_part1';
MLI18n::gi()->{'hitmeister_prepareform_max_length_part2'} = 'hitmeister_prepareform_max_length_part2';
MLI18n::gi()->{'hitmeister_prepareform_category'} = 'hitmeister_prepareform_category';
MLI18n::gi()->{'hitmeister_prepareform_title'} = 'hitmeister_prepareform_title';
MLI18n::gi()->{'hitmeister_prepareform_description'} = 'hitmeister_prepareform_description';
MLI18n::gi()->{'hitmeister_prepareform_warranty_description'} = 'hitmeister_prepareform_warranty_description';
MLI18n::gi()->{'hitmeister_prepareform_delivery_description'} = 'hitmeister_prepareform_delivery_description';
MLI18n::gi()->{'hitmeister_prepareform_payment_description'} = 'hitmeister_prepareform_payment_description';
MLI18n::gi()->{'hitmeister_prepareform_setdate'} = 'hitmeister_prepareform_setdate';
MLI18n::gi()->{'hitmeister_prepareform_labelprice'} = 'hitmeister_prepareform_labelprice';
MLI18n::gi()->{'hitmeister_prepareform_labelfixprice'} = 'hitmeister_prepareform_labelfixprice';
MLI18n::gi()->{'hitmeister_prepareform_valuehintlprice'} = 'hitmeister_prepareform_valuehintlprice';
MLI18n::gi()->{'hitmeister_prepareform_paymentmethods'} = 'hitmeister_prepareform_paymentmethods';
MLI18n::gi()->{'hitmeister_prepareform_defaulttemplate'} = 'hitmeister_prepareform_defaulttemplate';
MLI18n::gi()->{'hitmeister_prepareform_days'} = 'hitmeister_prepareform_days';
MLI18n::gi()->{'hitmeister_after_delete'} = 'hitmeister_after_delete';
MLI18n::gi()->{'hitmeister_prepare_apply'} = 'Create New Products';
