<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'priceminister_prepare_form__legend__details'} = 'priceminister_prepare_form__legend__details';
MLI18n::gi()->{'priceminister_prepare_form__legend__delivery'} = 'priceminister_prepare_form__legend__delivery';
MLI18n::gi()->{'priceminister_prepare_form__legend__categories'} = 'priceminister_prepare_form__legend__categories';
MLI18n::gi()->{'priceminister_prepare_form__field__categories__label'} = 'priceminister_prepare_form__field__categories__label';
MLI18n::gi()->{'priceminister_prepare_form__field__primarycategory__label'} = 'priceminister_prepare_form__field__primarycategory__label';
MLI18n::gi()->{'priceminister_prepare_form__field__catattributes__label'} = 'priceminister_prepare_form__field__catattributes__label';
MLI18n::gi()->{'priceminister_prepare_form__field__itemtitle__label'} = 'priceminister_prepare_form__field__itemtitle__label';
MLI18n::gi()->{'priceminister_prepare_form__field__itemtitle__hint'} = 'priceminister_prepare_form__field__itemtitle__hint';
MLI18n::gi()->{'priceminister_prepare_form__field__description__label'} = 'priceminister_prepare_form__field__description__label';
MLI18n::gi()->{'priceminister_prepare_form__field__description__hint'} = 'priceminister_prepare_form__field__description__hint';
MLI18n::gi()->{'priceminister_prepare_form__field__brand__label'} = 'priceminister_prepare_form__field__brand__label';
MLI18n::gi()->{'priceminister_prepare_form__field__images__label'} = 'priceminister_prepare_form__field__images__label';
MLI18n::gi()->{'priceminister_prepare_form__field__comparasionunit__label'} = 'priceminister_prepare_form__field__comparasionunit__label';
MLI18n::gi()->{'priceminister_prepare_form__field__location__label'} = 'priceminister_prepare_form__field__location__label';
MLI18n::gi()->{'priceminister_prepare_form__field__price__label'} = 'priceminister_prepare_form__field__price__label';
MLI18n::gi()->{'priceminister_prepare_form__field__shippingtime__label'} = 'priceminister_prepare_form__field__shippingtime__label';
MLI18n::gi()->{'priceminister_prepare_form__field__shippingcost__label'} = 'priceminister_prepare_form__field__shippingcost__label';
MLI18n::gi()->{'priceminister_prepareform_max_length_part1'} = 'priceminister_prepareform_max_length_part1';
MLI18n::gi()->{'priceminister_prepareform_max_length_part2'} = 'priceminister_prepareform_max_length_part2';
MLI18n::gi()->{'priceminister_prepare_form_category'} = 'priceminister_prepare_form_category';
MLI18n::gi()->{'priceminister_prepare_form_itemtitle'} = 'priceminister_prepare_form_itemtitle';
MLI18n::gi()->{'priceminister_prepare_form_description'} = 'priceminister_prepare_form_description';
MLI18n::gi()->{'priceminister_prepareform_category_attribute'} = 'priceminister_prepareform_category_attribute';
MLI18n::gi()->{'priceminister_category_no_attributes'} = 'priceminister_category_no_attributes';
