<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNamePriceMinister'} = 'Priceminister';
MLI18n::gi()->{'ML_PRICEMINISTER_TEXT_NO_MATCHED_PRODUCTS'} = 'Les produits n\'ont pas encore été préparés pour Priceminister. Avant de pouvoir les télécharger, ils doivent être préparés dans la rubrique "Préparer les articles". <br>
Dans le cas où vous ne retrouveriez pas l\'un de vos articles sous cet onglet, vérifiez qu\'il soit bien actifs et que vous ayez coché l\'option "Ne prendre en compte que les articles actifs" dans la configuration de votre boutique.';
MLI18n::gi()->{'priceminister_upload_explanation'} = 'Les nouvelles insertions sont traitées dans l\'espace d\'une heure par Priceminister. Une fois les offres validées, elles apparaîtront dans votre compte vendeur Priceminister.';
MLI18n::gi()->{'priceminister_pre_upload_popup'} = 'Priceminister ne permet pas aux vendeurs d\'excéder les 20.000 articles. <br> Voulez-vous poursuivre le téléchargement ou annuler et refaire une sélection.';
MLI18n::gi()->{'priceminister_label_not_matched'} = 'ne pas appairer ';
MLI18n::gi()->{'priceminister_label_title'} = 'Titre Priceminister';
MLI18n::gi()->{'priceminister_category'} = 'Catégorie PriceMinister';
MLI18n::gi()->{'priceminister_label_item_id'} = 'Référence Priceminister ';
MLI18n::gi()->{'priceminister_search_by_keywords'} = 'Rechercher par mots-clé';
MLI18n::gi()->{'priceminister_search_by_ean'} = 'Rechercher par code EAN';
MLI18n::gi()->{'priceminister_search_by_category'} = 'Rechercher par catégorie';
MLI18n::gi()->{'priceminister_search_by_pm_productid'} = 'Rechercher avec la référence de produit de Priceminister';
