<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'PriceMinister_CheckinForm__Price'} = 'Prix';
MLI18n::gi()->{'PriceMinister_CheckinForm__Amount'} = 'Quantité ';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShippingTime'} = 'Livraison (en jours)';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShopPrice'} = 'Boutique';
MLI18n::gi()->{'PriceMinister_CheckinForm__SuggestedPrice'} = 'Calculé (d\'après la configuration)';
MLI18n::gi()->{'PriceMinister_CheckinForm__HitPrice'} = 'Meilleur prix';
MLI18n::gi()->{'PriceMinister_CheckinForm__AvailibleAmount'} = 'Disponible';
MLI18n::gi()->{'PriceMinister_CheckinForm__SuggestedAmount'} = 'Calculé (d\'après la configuration)';
MLI18n::gi()->{'PriceMinister_CheckinForm__Condition'} = 'État de l\'article';
MLI18n::gi()->{'PriceMinister_CheckinForm__ListingType'} = 'Type de listing';
MLI18n::gi()->{'PriceMinister_CheckinForm__Conditions__new'} = 'Neuf';
MLI18n::gi()->{'PriceMinister_CheckinForm__Conditions__not_specified'} = 'Pas spécifié';
MLI18n::gi()->{'PriceMinister_CheckinForm__Conditions__used'} = 'D\'occasion';
MLI18n::gi()->{'PriceMinister_CheckinForm__BuyingMode'} = 'Mode d\'achat';
MLI18n::gi()->{'PriceMinister_CheckinForm__BuyingModes__buy_it_now'} = 'Achetez maintenant';
MLI18n::gi()->{'PriceMinister_CheckinForm__BuyingModes__auction'} = 'Enchères';
MLI18n::gi()->{'PriceMinister_CheckinForm__BuyingModes__classified'} = 'Classé';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShippingMode'} = 'Mode de livraison';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShippingModes__custom'} = 'Personnalisé';
MLI18n::gi()->{'PriceMinister_CheckinForm__ShippingModes__not_specified'} = 'Pas spécifié ';
