<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_SKU'} = 'SKU';
MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_NAME'} = 'Titre sur Priceminister ';
MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_SHOP_PREIS'} = 'Prix sur Priceminister';
MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_MARKETPLACE_PREIS'} = 'Prix sur la place de marché';
MLI18n::gi()->{'PRICEMINISTER_ML_LABEL_ARTICLE_MARKETPLACE_QUANTITY'} = 'Stock <br />Boutique / Priceminister';
MLI18n::gi()->{'priceminister_inventory_listing_status'} = 'Statut';
MLI18n::gi()->{'priceminister_inventory_is_split'} = 'priceminister_inventory_is_split';
MLI18n::gi()->{'priceminister_inventory_reject_message'} = 'Veuillez contacter le support de Priceminister pour savoir pourquoi l\'article a été rejeté.';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparés avec succès';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparés ';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Articles préparés non vérifiés ';
MLI18n::gi()->{'Priceminister_Productlist_Filter_aPreparedStatus__OK'} = 'Préparés avec succès';
MLI18n::gi()->{'Priceminister_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparés ';
MLI18n::gi()->{'Priceminister_Productlist_Filter_aPreparedStatus__OPEN'} = 'Articles préparés non vérifiés ';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__Chinese'} = 'Enchère';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Prix fixe';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Prix fixe (Boutique Priceminister)';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__manual'} = 'Appariement manuel';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__auto'} = 'Appariement automatique';
MLI18n::gi()->{'Priceminister_Productlist_Cell_aPreparedType__apply'} = 'Créer un nouveau produit';
MLI18n::gi()->{'Priceminister_Productlist_Header_sPreparedType'} = 'Type de préparation';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Manual_Title_Single'} = 'Appariement simple';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Manual_Title_Multi'} = 'Appariement multiple';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Title'} = 'Appariement des attributs';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Summary'} = '%d Ont été classés avec succès.<br/><br/>
%d Articles n\'ont pas pu être classé.<br/>
%d articles ont plusieurs résultats. %s';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Summary_Categories'} = '<br/>Vous devez apparier les attributs de cette catégorie : %s.';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Manual_Desc'} = 'Avant de mettre un article en vente sur PriceMinister, il faut à l’aide de son code EAN et de son titre
vérifier son référencement préalable sur la plate-forme. Pour cela cochez l’article de votre boutique dont vous voulez apparier le référencement.<br>
<br>
Vous obtenez alors un résultat positif ou négatif détaillé, qui vous permet de choisir le type d’appariement.

Le temps de réponse peut être long.';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Desc'} = 'Les articles, que vous avez sélectionnés vont être préparés en arrière plan: Chaque article va être apparié automatiquement grace aux numéros EAN des articles correspondants sur Priceminister et aux numéros EAN pré-enregistrés pour cet article.<br/ ><br/ > Il est donc primordial de mettre à jour régulièrement les numéros EAN de chaque produit.';
MLI18n::gi()->{'PriceMinister_Productlist_Match_Auto_Confirm'} = 'L\'appariement automatique se fait uniquement par la comparaison des codes EAN. Il est possible que votre offre soit apparié avec une offre de qualité inférieure au niveau de la description et des photos, ce qui va alors provoquer de mauvais résultats, plus mauvais qu\'avec un classement (matching) manuel.<br/ ><br/ > RedGecko décline alors toutes responsabilités en cas d\'inexactitude de l\'article proposé.';
