<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'MOrderID'} = '{#_platformName_#} ID do Pedido';
MLI18n::gi()->{'MPreviousOrderID'} = '{#_platformName_#} ID do Pedido';
MLI18n::gi()->{'MPreviousOrderIDS'} = '{#_platformName_#} ID de todos Pedidos';
MLI18n::gi()->{'BuyerUsername'} = '{#_platformName_#} Nome do usuário';
