<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'MOrderID'} = '{#_platformName_#} Order ID';
MLI18n::gi()->{'MPreviousOrderID'} = '{#_platformName_#} Order ID';
MLI18n::gi()->{'MPreviousOrderIDS'} = '{#_platformName_#} Order ID';
MLI18n::gi()->{'BuyerUsername'} = '{#_platformName_#} User Name';
