<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sLog_timeStamp'} = 'Instante';
MLI18n::gi()->{'sLog_delete'} = 'Apagar registro de log';
MLI18n::gi()->{'aLog_ordersSync__title'} = 'Sincronização de Pedidos';
MLI18n::gi()->{'aLog_ordersSync__info__title'} = 'processo';
MLI18n::gi()->{'aLog_ordersSync__info__values__createOrder'} = 'Novo pedido';
MLI18n::gi()->{'aLog_ordersSync__info__values__extendOrder'} = 'Pedido expandido';
MLI18n::gi()->{'aLog_ordersSync__marketplace'} = 'Marketplace';
MLI18n::gi()->{'aLog_ordersSync__orderno_marketplace'} = 'Número do pedido (Marketplace)';
MLI18n::gi()->{'aLog_ordersSync__orderno_shop'} = 'Número do pedido (loja)';
MLI18n::gi()->{'aLog_ordersSync__status'} = 'Situação do pedido';
