<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2021 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'etsy_config_account_title'} = 'Login Details';
MLI18n::gi()->{'etsy_config_account_prepare'} = 'Item preparation';
MLI18n::gi()->{'etsy_config_account_price'} = 'Price calculation';
MLI18n::gi()->{'etsy_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'etsy_config_account_orderimport'} = 'Order import';

MLI18n::gi()->{'etsy_configform_sync_values'} = array(
    'no' => '{#i18n:configform_sync_value_no#}',
    'auto_zero_stock' => 'Automatic Synchronization incl. Zero-Stock (recommended)',
    'auto' => 'Automatic Synchronization without Zero-Stock',
);

MLI18n::gi()->{'etsy_configform_sync_nozerostock_popup_label'} = 'Automatic Synchronization without Zero-Stock';
MLI18n::gi()->{'etsy_configform_sync_nozerostock_popup_text'} = 'Products, which dropped below shop-stock-level "1", will be set as “inactive” on Etsy and will not be activated again. This prevents of the risk of unintentional Etsy fees.';
MLI18n::gi()->{'etsy_configform_sync_zerostock_popup_label'} = 'Automatic Synchronization incl. Zero-Stock (recommended)';
MLI18n::gi()->{'etsy_configform_sync_zerostock_popup_text'} = 'This option also activates or deactivates your offers on Etsy if the stock in your Online Store exceeds “0”  or if becomes less than “1” . Etsy will charge for each re-activation';

MLI18n::gi()->{'etsy_config_carrier_option_group_additional_option'} = 'Additional option:';
MLI18n::gi()->{'etsy_config_carrier_option_group_marketplace_carrier'} = 'Select Marketplace Supported Carrier:';
MLI18n::gi()->{'etsy_config_free_text_attributes_opt_group'} = 'Free text fields';
MLI18n::gi()->{'etsy_config_free_text_attributes_opt_group_value'} = 'Match it to free text field on specific order';
MLI18n::gi()->{'etsy_config_carrier_option_matching_option'} = 'Match marketplace supported carrier with carriers defined in shop-system';
MLI18n::gi()->{'etsy_config_carrier_matching_title_marketplace_carrier'} = 'Marketplace supported carriers';
MLI18n::gi()->{'etsy_config_carrier_matching_title_shop_carrier'} = 'Carriers defined in the shop-system (shipping module)';
MLI18n::gi()->{'etsy_config_item_preparation_readiness_state_ready_to_ship'} = 'Ready To Ship';
MLI18n::gi()->{'etsy_config_item_preparation_readiness_state_made_to_order'} = 'Made To Order';

