<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEtsy'} = 'Etsy';
MLI18n::gi()->{'etsy_prepare_description_not_valid'} = 'Item description is too long. Maximum number of characters is 63000.';
MLI18n::gi()->{'etsy_prepare_images_not_valid'} = 'The picture is too big. The maximum allowed image size is 3000 x 3000 px.';
MLI18n::gi()->{'etsy_prepare_images_not_exist'} = 'There must be at least one image for the item !';
MLI18n::gi()->{'etsy_prepare_description_not_exist'} = 'Item description is too short.';
MLI18n::gi()->{'etsy_prepare_price_not_valid'} = 'Minimum item price on Etsy is 0.17£';
MLI18n::gi()->{'etsy_prepare_quantity_not_valid'} = 'The stock for a product must not be larger than 999.';
MLI18n::gi()->{'etsy_prepare_empty_list_processing_profiles'} = 'Please create a processing profile first in your Etsy account';

MLI18n::gi()->{'etsy_inventory_listing_status_new'} = 'Product will be created';
MLI18n::gi()->{'etsy_inventory_listing_status_active'} = 'Active';
MLI18n::gi()->{'etsy_inventory_listing_status_inactive'} = 'Inactive';
MLI18n::gi()->{'etsy_inventory_listing_status_expired'} = 'Expired';
MLI18n::gi()->{'etsy_inventory_listing_status_draft'} = 'Draft';
MLI18n::gi()->{'etsy_inventory_listing_status_sold_out'} = 'Sold Out';

MLI18n::gi()->{'etsy_checkin_purge_popup_text'} = '
<p><strong>Please note:</strong> You are about to completely replace your inventory on Etsy. This process first completely deletes your marketplace inventory and then replaces it with the items selected here.</p>
<p>Etsy charges fees for creating new listings. Contact the Etsy support if you have any questions about your Etsy plan.</p>
<p>Do you really want to proceed?</p>
';
MLI18n::gi()->{'etsy_checkin_popup_text'} = '<p><strong>Please note:</strong> Etsy charges fees for creating new listings. Contact the Etsy support if you have any questions about your Etsy plan.</p>';

MLI18n::gi()->{'ML_ETSY_PROCESSING_PROFILE_UPDATE_HINT'} = '<h3>Important Notice After Update: Processing Profiles Required</h3>
    <p><strong>Why is this step necessary?</strong></p>
    <p>Etsy now requires processing profiles (Processing Profiles) to be specified for all items. These profiles contain important information such as:</p>
    <ul>
        <li>Are your items created after purchase or ready for immediate shipping? This information helps buyers understand the expected shipping timeframe.</li>
        <li>Minimum and maximum processing time</li>
    </ul>
    <p><strong>What do you need to do now?</strong></p>
    <ol>
        <li>Create processing profiles directly on Etsy:<br>
            &rarr; <a href="https://www.etsy.com/your/shops/me/tools/shipping-profiles" target="_blank">https://www.etsy.com/your/shops/me/tools/shipping-profiles</a><br>
            or in the Etsy portal under <strong>Settings &rarr; Shipping Settings</strong></li>
        <li>Wait a few minutes for the profiles to synchronize</li>
        <li>Refresh the magnalister page (F5)</li>
        <li>Go to <strong>Configuration &rarr; Product Preparation &rarr; Processing Profiles</strong> and select your default profile</li>
        <li>After that you can prepare and upload your products again</li>
    </ol>
    <p><strong>Status of your products:</strong> All existing products have received the status "Preparation required again" and must be prepared again after configuring the processing profile before they can be uploaded.</p>
    <p><em>You can dismiss this message by clicking the close button.</em></p>';
