<?php
/*
 * 888888ba                 dP  .88888.                    dP
 * 88    `8b                88 d8'   `88                   88
 * 88aaaa8P' .d8888b. .d888b88 88        .d8888b. .d8888b. 88  .dP  .d8888b.
 * 88   `8b. 88ooood8 88'  `88 88   YP88 88ooood8 88'  `"" 88888"   88'  `88
 * 88     88 88.  ... 88.  .88 Y8.   .88 88.  ... 88.  ... 88  `8b. 88.  .88
 * dP     dP `88888P' `88888P8  `88888'  `88888P' `88888P' dP   `YP `88888P'
 *
 *                          m a g n a l i s t e r
 *                                      boost your Online-Shop
 *
 * -----------------------------------------------------------------------------
 * (c) 2010 - 2024 RedGecko GmbH -- http://www.redgecko.de
 *     Released under the MIT License (Expat)
 * -----------------------------------------------------------------------------
 */

/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_prepare_form__legend__language'} = 'Langue';
MLI18n::gi()->{'hitmeister_prepare_form__legend__details'} = 'Détails du produit';
MLI18n::gi()->{'hitmeister_prepare_form__legend__templates'} = 'Modèles de description';
MLI18n::gi()->{'hitmeister_prepare_form__legend__categories'} = 'Catégorie';
MLI18n::gi()->{'hitmeister_prepare_form__legend__price'} = 'Prix & Durée ';
MLI18n::gi()->{'hitmeister_prepare_form__legend__shipping'} = 'Expédition';
MLI18n::gi()->{'hitmeister_prepare_form__legend__promotion'} = 'Promotion';
MLI18n::gi()->{'hitmeister_prepare_form__legend__other'} = 'Plus de réglages';
MLI18n::gi()->{'hitmeister_prepare_form__field__categories__label'} = 'Catégorie Kaufland';
MLI18n::gi()->{'hitmeister_prepare_form__field__primarycategory__label'} = '1. Catégorie place de marché';
MLI18n::gi()->{'hitmeister_prepare_form__field__articlecondition__label'} = 'État du produit';
MLI18n::gi()->{'hitmeister_prepare_form__field__listinglangs__label'} = 'Langue de l\'offre';
MLI18n::gi()->{'hitmeister_prepare_form__field__langde__label'} = 'DE';
MLI18n::gi()->{'hitmeister_prepare_form__field__langfr__label'} = 'FR';
MLI18n::gi()->{'hitmeister_prepare_form__field__detitle__label'} = 'Titre (en allemand)';
MLI18n::gi()->{'hitmeister_prepare_form__field__detitle__hint'} = 'hitmeister_prepare_form__field__detitle__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__detitle__optional__checkbox__labelNegativ'} = 'Reprendre toujours le nom actuel de l\'article de la boutique en ligne';
MLI18n::gi()->{'hitmeister_prepare_form__field__desubtitle__label'} = 'Sous-titre (allemand)';
MLI18n::gi()->{'hitmeister_prepare_form__field__desubtitle__hint'} = 'hitmeister_prepare_form__field__desubtitle__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__desubtitle__optional__select__false'} = 'Ne pas transmettre';
MLI18n::gi()->{'hitmeister_prepare_form__field__desubtitle__optional__select__true'} = 'Transmettre';
MLI18n::gi()->{'hitmeister_prepare_form__field__dedescription__label'} = 'Description (en allemand)';
MLI18n::gi()->{'hitmeister_prepare_form__field__dedescription__hint'} = 'Espace réservé disponible <br>pour la description du produit:<dl><dt style="font-weight:bold, color:black">#TITLE#</dt><dd>Nom du produit (Titre)</dd><dt style="font-weight:bold, color:black">#ARTNR#</dt><dd>Numéro de l\'article</dd><dt style="font-weight:bold, color:black">#PID#</dt><dd>Produit-ID</dd><dt style="font-weight:bold, color:black">#SHORTDESCRIPTION#</dt><dd>petite description deu produit en magasin</dd><dt style="font-weight:bold, color:black">#DESCRIPTION#</dt><dd>Description du Shop</dd><dt style="font-weight:bold, color:black">#PICTURE1#</dt><dd>première photo du produit</dd><dt style="font-weight:bold, color:black">#PICTURE2# etc.</dt><dd>deuxième photo du produit, avec #PICTURE3#, #PICTURE4# etc. vous pouvez envoyer d\'autres photos, autant que disponibles en boutique.</dd></dl>';
MLI18n::gi()->{'hitmeister_prepare_form__field__dedescription__optional__checkbox__labelNegativ'} = 'Reprendre toujours la description de l\'article de la boutique en ligne.';
MLI18n::gi()->{'hitmeister_prepare_form__field__frtitle__label'} = 'Titre (en français)';
MLI18n::gi()->{'hitmeister_prepare_form__field__frtitle__hint'} = 'hitmeister_prepare_form__field__frtitle__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__frtitle__optional__checkbox__labelNegativ'} = 'Reprendre toujours le nom de l\'article de la boutique en ligne.';
MLI18n::gi()->{'hitmeister_prepare_form__field__frsubtitle__label'} = 'Sous-titre (en français)';
MLI18n::gi()->{'hitmeister_prepare_form__field__frsubtitle__hint'} = 'hitmeister_prepare_form__field__frsubtitle__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__frsubtitle__optional__select__false'} = 'Ne pas transmettre';
MLI18n::gi()->{'hitmeister_prepare_form__field__frsubtitle__optional__select__true'} = 'Transmettre';
MLI18n::gi()->{'hitmeister_prepare_form__field__frdescription__label'} = 'Description (en français)';
MLI18n::gi()->{'hitmeister_prepare_form__field__frdescription__hint'} = 'Espace réservé disponible <br>pour la description du produit:<dl><dt style="font-weight:bold, color:black">#TITLE#</dt><dd>Nom du produit (Titre)</dd><dt style="font-weight:bold, color:black">#ARTNR#</dt><dd>Numéro de l\'article</dd><dt style="font-weight:bold, color:black">#PID#</dt><dd>Produit-ID</dd><dt style="font-weight:bold, color:black">#SHORTDESCRIPTION#</dt><dd>petite description deu produit en magasin</dd><dt style="font-weight:bold, color:black">#DESCRIPTION#</dt><dd>Description du Shop</dd><dt style="font-weight:bold, color:black">#PICTURE1#</dt><dd>première photo du produit</dd><dt style="font-weight:bold, color:black">#PICTURE2# etc.</dt><dd>deuxième photo du produit, avec #PICTURE3#, #PICTURE4# etc. vous pouvez envoyer d\'autres photos, autant que disponibles en boutique.</dd></dl>';
MLI18n::gi()->{'hitmeister_prepare_form__field__frdescription__optional__checkbox__labelNegativ'} = 'Veuillez toujours utiliser la description actuelle de la boutique en ligne. ';
MLI18n::gi()->{'hitmeister_prepare_form__field__images__label'} = 'Images du produit';
MLI18n::gi()->{'hitmeister_prepare_form__field__images__hint'} = 'Maximum de 10 images de produits';
MLI18n::gi()->{'hitmeister_prepare_form__field__descriptiontemplate__label'} = 'Modèles du client';
MLI18n::gi()->{'hitmeister_prepare_form__field__warranty__label'} = 'Garantie';
MLI18n::gi()->{'hitmeister_prepare_form__field__warrantycondition__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__warrantyconditionajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__warrantydescription__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__buyingmode__label'} = 'Type de vente aux enchères';
MLI18n::gi()->{'hitmeister_prepare_form__field__buyingmode__hint'} = 'hitmeister_prepare_form__field__buyingmode__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__price__label'} = 'Prix';
MLI18n::gi()->{'hitmeister_prepare_form__field__fixpriceajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__fixprice__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enablebuynowpriceajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enablebuynowpriceajax__valuehint'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enablebuynowprice__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enablebuynowprice__valuehint'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__auction__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__priceajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__priceforauction__label'} = 'Prix de départ';
MLI18n::gi()->{'hitmeister_prepare_form__field__priceincrement__label'} = 'Augmentation de l\'offre';
MLI18n::gi()->{'hitmeister_prepare_form__field__durationcontainer__label'} = 'Durée';
MLI18n::gi()->{'hitmeister_prepare_form__field__durationcontainer__hint'} = 'hitmeister_prepare_form__field__durationcontainer__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__duration__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__startdate__label'} = 'Date de début';
MLI18n::gi()->{'hitmeister_prepare_form__field__endtime__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__enddate__label'} = 'Fin de la durée';
MLI18n::gi()->{'hitmeister_prepare_form__field__maxrelistcountcontainer__label'} = 'Réactiver une offre';
MLI18n::gi()->{'hitmeister_prepare_form__field__maxrelistcount__label'} = 'Combien de fois votre offre doit-elle être réactivée?';
MLI18n::gi()->{'hitmeister_prepare_form__field__payment__label'} = 'Type de paiement';
MLI18n::gi()->{'hitmeister_prepare_form__field__payment__hint'} = 'hitmeister_prepare_form__field__payment__hint';
MLI18n::gi()->{'hitmeister_prepare_form__field__paymentmethods__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__paymentmethodsajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__paymentdescription__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__delivery__label'} = 'Mode de livraison';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliverycondition__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliveryconditionajax__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliverypackage__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliverydescription__label'} = '';
MLI18n::gi()->{'hitmeister_prepare_form__field__deliverycost__label'} = 'Frais de port';
MLI18n::gi()->{'hitmeister_prepare_form__field__availabilitycontainer__label'} = 'Délai de livraison ';
MLI18n::gi()->{'hitmeister_prepare_form__field__availability__label'} = 'Disponibilité de l\'article après réception du paiement';
MLI18n::gi()->{'hitmeister_prepare_form__field__promotion__label'} = 'Promotion';
MLI18n::gi()->{'hitmeister_prepare_form__field__firstpromotion__label'} = 'Paquet de promotion';
MLI18n::gi()->{'hitmeister_prepare_form__field__firstpromotion__hint'} = '<span style="color:#e31a1c;">Les promotions ne sont pas gratuites. Veuillez vérifier, s\'il vous plaît, les prix sur Kaufland.</span>';
MLI18n::gi()->{'hitmeister_prepare_form__field__secondpromotion__label'} = 'Haut de la page';
MLI18n::gi()->{'hitmeister_prepare_form__field__secondpromotion__hint'} = '<span style="color:#e31a1c;">Les promotions ne sont pas gratuites. Veuillez vérifier, s\'il vous plaît, les prix sur Kaufland.</span>';
MLI18n::gi()->{'hitmeister_prepareform_max_length_part1'} = 'Longueur max de';
MLI18n::gi()->{'hitmeister_prepareform_max_length_part2'} = 'L\'attribut est';
MLI18n::gi()->{'hitmeister_prepareform_category'} = 'La catégorie de l\'attribut est obligatoire.';
MLI18n::gi()->{'hitmeister_prepareform_title'} = 'Le titre de l\'attribut est obligatoire.';
MLI18n::gi()->{'hitmeister_prepareform_description'} = 'La description de l\'attribut est obligatoire';
MLI18n::gi()->{'hitmeister_prepareform_warranty_description'} = 'La garantie de description de l\'attribut est obligatoire.';
MLI18n::gi()->{'hitmeister_prepareform_delivery_description'} = 'La livraison de la description de l\'attribut est obligatoire';
MLI18n::gi()->{'hitmeister_prepareform_payment_description'} = 'Le paiement de la description de l\'attribut est obligatoire';
MLI18n::gi()->{'hitmeister_prepareform_setdate'} = 'La date de l\'attribut est obligatoire';
MLI18n::gi()->{'hitmeister_prepareform_labelprice'} = 'Prix est calculé selon le prix de la configuration.';
MLI18n::gi()->{'hitmeister_prepareform_labelfixprice'} = 'Acheter le prix maintenant';
MLI18n::gi()->{'hitmeister_prepareform_valuehintlprice'} = 'Activez le prix d\'achat immédiat (le prix sera calculé selon le prix de la configuration.)';
MLI18n::gi()->{'hitmeister_prepareform_paymentmethods'} = 'Modes de  paiement non valide.';
MLI18n::gi()->{'hitmeister_prepareform_defaulttemplate'} = 'Pas de modèle (template)';
MLI18n::gi()->{'hitmeister_prepareform_days'} = 'Jours';
MLI18n::gi()->{'hitmeister_after_delete'} = 'L\'opération de suppression peut prendre jusqu\'à 15 minutes.';
