<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameCdiscount'} = 'Cdiscount';
MLI18n::gi()->{'cdiscount_label_title'} = 'Cdiscount Title';
MLI18n::gi()->{'cdiscount_category'} = 'Cdiscount Category';
MLI18n::gi()->{'cdiscount_label_item_id'} = 'Item ID';
MLI18n::gi()->{'cdiscount_search_by_title'} = 'Search by title';
MLI18n::gi()->{'cdiscount_search_by_ean'} = 'Search by EAN';
MLI18n::gi()->{'cdiscount_label_not_matched'} = 'don\'t match';
MLI18n::gi()->{'cdiscount_upload_explanation'} = 'As a rule, the uploaded products are placed on Cdiscount within a few hours.
If the product is not already available on Cdiscount, it could take up to 24 hours.
Afterwards the articles are to be found in your Cdiscount merchant account.';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_marketplace_carrier'} = 'Shipping Carriers suggested by CDiscount';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_carrier'} = 'Shipping Carriers from webshop free text fields for orders';
MLI18n::gi()->{'cdiscount_config_carrier_option_matching_option_carrier'} = 'Match shipping carriers suggested by CDiscount with carriers defined in webshop system (shipping module)';
MLI18n::gi()->{'cdiscount_config_carrier_option_freetext_option_carrier'} = 'Generally, apply shipping carrier from text field';
MLI18n::gi()->{'cdiscount_config_carrier_matching_title_shop_carrier'} = 'Shipping carrier defined in webshop system (shipping module)';
MLI18n::gi()->{'cdiscount_config_carrier_matching_title_marketplace_carrier'} = 'Shipping Carrier suggested by CDiscount';
MLI18n::gi()->{'cdiscount_config_carrier_option_orderfreetextfield_option'} = 'magnalister adds a free text field in the order details';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_additional_option'} = 'Additional options';
MLI18n::gi()->{'cdiscount_config_carrier_matching_title_marketplace_shipmethod'} = 'Shipping method suggested by CDiscount';
MLI18n::gi()->{'cdiscount_config_carrier_option_freetext_option_shipmethod'} = 'Generally, apply shipping method from text field';
MLI18n::gi()->{'cdiscount_config_carrier_option_matching_option_shipmethod'} = 'Match shipping method with entries from webshop shipping module';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_shipmethod'} = 'Shipping method from webshop free text field for orders';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_carrier'} = 'Shipping Carriers from webshop free text fields for orders';
MLI18n::gi()->{'cdiscount_config_carrier_option_group_shopfreetextfield_option_shipmethod'} = 'Shipping method from webshop free text field for orders';
