<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'cdiscount_inventory_listing_quantity'} = 'Stock: Shop / Cdiscount';
MLI18n::gi()->{'cdiscount_inventory_listing_price'} = 'Cdiscount price';
MLI18n::gi()->{'cdiscount_inventory_listing_status'} = 'Status';
MLI18n::gi()->{'cdiscount_inventory_listing_status_new'} = 'New';
MLI18n::gi()->{'cdiscount_inventory_listing_status_update'} = 'Cdiscount is updating item';
MLI18n::gi()->{'cdiscount_inventory_listing_status_waiting'} = 'Submission to Cdiscount in progress';
MLI18n::gi()->{'cdiscount_inventory_listing_status_waiting_update'} = 'Cdiscount is processing item';
MLI18n::gi()->{'cdiscount_inventory_listing_status_active'} = 'Active';
