<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Cdiscount_Label_sAutoMatchSuccess'} = 'Products with EAN-field are prepared.';
MLI18n::gi()->{'CDISCOUNT_BUTTON_LABEL_DELETE_COMPLETE_LOG'} = 'Delete complete log';
MLI18n::gi()->{'cdiscount_prepare_apply'} = 'Apply new products';
