<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'cdiscount_prepare_match_manual__legend__unit'} = 'General Configuration';
MLI18n::gi()->{'cdiscount_prepare_match_manual__legend__manualmatching'} = 'Matching';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__price__label'} = 'Price';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__itemcondition__label'} = 'Condition';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__preparationtime__label'} = 'Preparation time';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__fee__label'} = 'Shipping fee';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__shippingfeestandard__label'} = 'Shipping fee';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__shippingfeeextrastandard__label'} = 'Additional shipping fee';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__shippingfeetracked__label'} = 'Shipping fee';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__shippingfeeextratracked__label'} = 'Additional shipping fee';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__shippingfeeregistered__label'} = 'Shipping fee';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__shippingfeeextraregistered__label'} = 'Additional shipping fee';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__addfee__label'} = 'Additional shipping fee';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__shipping_time_standard__label'} = 'Standard';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__shipping_time_tracked__label'} = 'Tracked';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__shipping_time_registered__label'} = 'Registered';
MLI18n::gi()->{'cdiscount_prepare_match_manual__field__comment__label'} = 'Hints to your article';
MLI18n::gi()->{'form_action_prepare_and_next'} = 'Save and Next';
MLI18n::gi()->{'cdiscount_label_product_at_cdiscount'} = 'product on Cdiscount';
