<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedStatus__OK__title'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Faultly prepared';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Prepared not checked';
MLI18n::gi()->{'Cdiscount_Productlist_Label_Price'} = 'Cdiscount price';
MLI18n::gi()->{'Cdiscount_Productlist_Filter_aPreparedStatus__OK'} = 'Prepared Status: Complete';
MLI18n::gi()->{'Cdiscount_Productlist_Filter_aPreparedStatus__ERROR'} = 'Faultly prepared';
MLI18n::gi()->{'Cdiscount_Productlist_Filter_aPreparedStatus__OPEN'} = 'Prepared nopt checked';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedType__Chinese'} = 'Auction (Chinese)';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fix price';
MLI18n::gi()->{'Cdiscount_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fix price (Cdiscount Store)';
MLI18n::gi()->{'Cdiscount_Productlist_Header_sPreparedType'} = 'Auction type';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Manual_Title_Single'} = 'Single Matching';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Manual_Title_Multi'} = 'Multi Matching';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Auto_Title'} = 'Automatic matching';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Auto_Summary'} = '%d articles successfully matched  <br/><br/>
%d articles could not be matched .<br/>
%d articles with multiple outcome.';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Manual_Desc'} = 'Try to match the EAN and title with articles on Cdiscount for shop-articles selected from the checkbox.<br/ ><br/ >
You receive a detailed result for successful and unsuccessful search and can individually select which hit should be used for matching.<br/ ><br/ >
Processing is very effective but also time-consuming.';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Auto_Desc'} = 'Checkbox-selected shop articles are processed automatically in the background:
The article will be matched automatically to an existing Cdiscount EAN with the assigned article-EAN .<br/ ><br/ >
Care of EAN numbers for each article is therefore required.';
MLI18n::gi()->{'Cdiscount_Productlist_Match_Auto_Confirm'} = 'Please note that automatic matching only effects via EAN check. It is possible that Cdiscount articles with description or pictures of lower quality will be matched. Because of that reason matching can result in a worse result than the manual matching.<br/ ><br/ >
RedGecko GmbH does not take liabilty for accuracy of matched products.';
