<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Shopware_Orderimport_CountryCodeIsEmptyError'} = 'Marketplace didn’t provide the country code for order {#mpOrderId#}. Please contact the magnalister support';
MLI18n::gi()->{'Shopware_Orderimport_CountryCodeDontExistsError'} = 'Country code {#ISO#} doesn\'t exist in your shop so we cannot import the order {#mpOrderId#}.';
MLI18n::gi()->{'Shopware_Orderimport_CustomerGroup_Notloggedin'} = 'Don\'t create customer account';
MLI18n::gi()->{'global_config_orderimport_field_customergroup_help'} = 'The customer group for the buyer accounts created when magnalister imports an order.<br />"No account": In Shopware, it&apos;s possible to create orders without a customer accounts.';
MLI18n::gi()->{'shopware_orderstatus_carrier_defaultField_value_shippingname'} = 'Pass shipping method as carrier';
