<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Shopware_Productlist_Filter_sStatus'} = 'Status';
MLI18n::gi()->{'Shopware_Productlist_Filter_sActive'} = 'active';
MLI18n::gi()->{'Shopware_Productlist_Filter_sInactive'} = 'inactive';
MLI18n::gi()->{'Shopware_Productlist_Filter_sManufacturer'} = 'Manufacturer';
MLI18n::gi()->{'Shopware_Productlist_Filter_sManufacturerId'} = 'Manufacturer part number';
MLI18n::gi()->{'Shopware_Productlist_Filter_sEan'} = 'EAN';
MLI18n::gi()->{'Shopware_Productlist_Filter_sCategory'} = 'Category';
MLI18n::gi()->{'prepare_product_keywords'} = '<p>Only tags are used.</p>';
